//go:build go1.22

// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/flate"
	"context"
	"encoding/base64"
	"encoding/json"
	"errors"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/oapi-codegen/runtime"
)

// Defines values for AccountStatus.
const (
	Closed AccountStatus = "closed"
	Open   AccountStatus = "open"
)

// Valid indicates whether the value is a known member of the AccountStatus enum.
func (e AccountStatus) Valid() bool {
	switch e {
	case Closed:
		return true
	case Open:
		return true
	default:
		return false
	}
}

// Defines values for BatchPostEntryResultStatus.
const (
	Created  BatchPostEntryResultStatus = "created"
	Existing BatchPostEntryResultStatus = "existing"
	Rejected BatchPostEntryResultStatus = "rejected"
)

// Valid indicates whether the value is a known member of the BatchPostEntryResultStatus enum.
func (e BatchPostEntryResultStatus) Valid() bool {
	switch e {
	case Created:
		return true
	case Existing:
		return true
	case Rejected:
		return true
	default:
		return false
	}
}

// Defines values for ErrorCode.
const (
	AccountClosed       ErrorCode = "account_closed"
	AccountNotFound     ErrorCode = "account_not_found"
	HolderConflict      ErrorCode = "holder_conflict"
	IdempotencyConflict ErrorCode = "idempotency_conflict"
	InsufficientFunds   ErrorCode = "insufficient_funds"
	InternalServerError ErrorCode = "internal_server_error"
	LedgerClosed        ErrorCode = "ledger_closed"
	LedgerNotFound      ErrorCode = "ledger_not_found"
)

// Valid indicates whether the value is a known member of the ErrorCode enum.
func (e ErrorCode) Valid() bool {
	switch e {
	case AccountClosed:
		return true
	case AccountNotFound:
		return true
	case HolderConflict:
		return true
	case IdempotencyConflict:
		return true
	case InsufficientFunds:
		return true
	case InternalServerError:
		return true
	case LedgerClosed:
		return true
	case LedgerNotFound:
		return true
	default:
		return false
	}
}

// Defines values for PayableAccountKind.
const (
	Payable PayableAccountKind = "payable"
)

// Valid indicates whether the value is a known member of the PayableAccountKind enum.
func (e PayableAccountKind) Valid() bool {
	switch e {
	case Payable:
		return true
	default:
		return false
	}
}

// Defines values for PostJournalEntryResponseState.
const (
	Posted PostJournalEntryResponseState = "posted"
)

// Valid indicates whether the value is a known member of the PostJournalEntryResponseState enum.
func (e PostJournalEntryResponseState) Valid() bool {
	switch e {
	case Posted:
		return true
	default:
		return false
	}
}

// Defines values for StatementDirection.
const (
	Credit StatementDirection = "credit"
	Debit  StatementDirection = "debit"
)

// Valid indicates whether the value is a known member of the StatementDirection enum.
func (e StatementDirection) Valid() bool {
	switch e {
	case Credit:
		return true
	case Debit:
		return true
	default:
		return false
	}
}

// Defines values for ValidationErrorCode.
const (
	ValidationErrorCodeValidationError ValidationErrorCode = "validation_error"
)

// Valid indicates whether the value is a known member of the ValidationErrorCode enum.
func (e ValidationErrorCode) Valid() bool {
	switch e {
	case ValidationErrorCodeValidationError:
		return true
	default:
		return false
	}
}

// Defines values for ValidationErrorDetailCode.
const (
	InvalidFormat ValidationErrorDetailCode = "invalid_format"
	InvalidType   ValidationErrorDetailCode = "invalid_type"
	InvalidValue  ValidationErrorDetailCode = "invalid_value"
	MaxLength     ValidationErrorDetailCode = "max_length"
	MinLength     ValidationErrorDetailCode = "min_length"
	Required      ValidationErrorDetailCode = "required"
	UnknownField  ValidationErrorDetailCode = "unknown_field"
)

// Valid indicates whether the value is a known member of the ValidationErrorDetailCode enum.
func (e ValidationErrorDetailCode) Valid() bool {
	switch e {
	case InvalidFormat:
		return true
	case InvalidType:
		return true
	case InvalidValue:
		return true
	case MaxLength:
		return true
	case MinLength:
		return true
	case Required:
		return true
	case UnknownField:
		return true
	default:
		return false
	}
}

// Defines values for ValidationErrorDetailLocation.
const (
	Body    ValidationErrorDetailLocation = "body"
	Header  ValidationErrorDetailLocation = "header"
	Path    ValidationErrorDetailLocation = "path"
	Query   ValidationErrorDetailLocation = "query"
	Request ValidationErrorDetailLocation = "request"
)

// Valid indicates whether the value is a known member of the ValidationErrorDetailLocation enum.
func (e ValidationErrorDetailLocation) Valid() bool {
	switch e {
	case Body:
		return true
	case Header:
		return true
	case Path:
		return true
	case Query:
		return true
	case Request:
		return true
	default:
		return false
	}
}

// AccountBalances defines model for AccountBalances.
type AccountBalances struct {
	// CreditsPending Total pending credit amount in minor units.
	//
	// Example: 0
	CreditsPending int64 `json:"credits_pending"`

	// CreditsPosted Total posted credit amount in minor units.
	//
	// Example: 10000
	CreditsPosted int64 `json:"credits_posted"`

	// DebitsPending Total pending debit amount in minor units.
	//
	// Example: 200
	DebitsPending int64 `json:"debits_pending"`

	// DebitsPosted Total posted debit amount in minor units.
	//
	// Example: 0
	DebitsPosted int64 `json:"debits_posted"`
}

// AccountReference Stable opaque reference assigned to an account by the ledger.
//
// Example: acct_01K33YV8M82N9MXP4E7J6B1QWK
type AccountReference = string

// AccountStatus Whether the payable account itself is open or closed.
//
// Example: open
type AccountStatus string

// AvailableBalance Derived available amount in minor units (credits_posted - debits_posted - debits_pending).
//
// Example: 9800
type AvailableBalance = int64

// BatchEntryError defines model for BatchEntryError.
type BatchEntryError struct {
	Code    ErrorCode `json:"code"`
	Message string    `json:"message"`
}

// BatchPostEntriesRequest defines model for BatchPostEntriesRequest.
type BatchPostEntriesRequest struct {
	// Entries Setting up a batch costs about what ten single postings cost, so a smaller batch is slower than posting the same entries to /entries one at a time. Send fewer than ten there instead.
	Entries []BatchPostEntryItem `json:"entries"`

	// Ledger Opaque identifier assigned to the ledger.
	//
	// Example: ngn_ng
	Ledger LedgerSlug `json:"ledger"`
}

// BatchPostEntriesResponse defines model for BatchPostEntriesResponse.
type BatchPostEntriesResponse struct {
	Results []BatchPostEntryResult `json:"results"`
}

// BatchPostEntryItem defines model for BatchPostEntryItem.
type BatchPostEntryItem struct {
	Description string     `json:"description"`
	EffectiveAt *time.Time `json:"effective_at,omitempty"`

	// IdempotencyKey Identifies this entry, not the request: the entry is the unit that is retried and the unit that comes back as `existing`. It shares one keyspace per ledger with the key sent to `POST /entries`, so the same key through either endpoint names the same entry.
	IdempotencyKey IdempotencyKey `json:"idempotency_key"`

	// Kind Business classification of a journal entry.
	Kind  JournalEntryKind       `json:"kind"`
	Lines []PostJournalEntryLine `json:"lines"`
}

// BatchPostEntryResult defines model for BatchPostEntryResult.
type BatchPostEntryResult struct {
	Error *BatchEntryError `json:"error"`

	// IdempotencyKey Caller-generated identifier used to make a ledger operation idempotent.
	//
	// Example: payment_123
	IdempotencyKey IdempotencyKey             `json:"idempotency_key"`
	JournalRef     *JournalRef                `json:"journal_ref"`
	Status         BatchPostEntryResultStatus `json:"status"`
}

// BatchPostEntryResultStatus defines model for BatchPostEntryResult.Status.
type BatchPostEntryResultStatus string

// CreatePayableAccountRequest defines model for CreatePayableAccountRequest.
type CreatePayableAccountRequest struct {
	ExternalID string `json:"external_id"`

	// Ledger Opaque identifier assigned to the ledger.
	//
	// Example: ngn_ng
	Ledger LedgerSlug `json:"ledger"`
	Name   string     `json:"name"`
}

// CreatePayableAccountResponse defines model for CreatePayableAccountResponse.
type CreatePayableAccountResponse struct {
	// Available Derived available amount in minor units (credits_posted - debits_posted - debits_pending).
	//
	// Example: 9800
	Available AvailableBalance `json:"available"`
	Balances  AccountBalances  `json:"balances"`
	ClosedAt  *time.Time       `json:"closed_at"`
	CreatedAt time.Time        `json:"created_at"`

	// ExternalID Example: merchant_123
	ExternalID string `json:"external_id"`

	// HolderReference Stable opaque reference assigned to a holder by the ledger.
	//
	// Example: hld_01K33YVADP5Z8B0T3X2Q91C6RH
	HolderReference HolderReference `json:"holder_reference"`

	// Kind Example: payable
	Kind PayableAccountKind `json:"kind"`

	// LedgerSlug Opaque identifier assigned to the ledger.
	//
	// Example: ngn_ng
	LedgerSlug LedgerSlug `json:"ledger_slug"`

	// Name Example: Acme Ltd
	Name string `json:"name"`

	// Reference Stable opaque reference assigned to an account by the ledger.
	//
	// Example: acct_01K33YV8M82N9MXP4E7J6B1QWK
	Reference AccountReference `json:"reference"`

	// Status Whether the payable account itself is open or closed.
	//
	// Example: open
	Status AccountStatus `json:"status"`
}

// ErrorCode defines model for ErrorCode.
type ErrorCode string

// ErrorInfo defines model for ErrorInfo.
type ErrorInfo struct {
	Code ErrorCode `json:"code"`
}

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	Error   ErrorInfo `json:"error"`
	Message string    `json:"message"`
}

// GetAccountResponse Example: {"available":9800,"balances":{"credits_pending":0,"credits_posted":10000,"debits_pending":200,"debits_posted":0},"closed_at":null,"created_at":"2026-09-08T10:30:00Z","holder_reference":"hld_01K33YVADP5Z8B0T3X2Q91C6RH","kind":"payable","ledger_slug":"ngn_ng","name":"Acme Ltd","reference":"acct_01K33YV8M82N9MXP4E7J6B1QWK","status":"open"}
type GetAccountResponse struct {
	// Available Derived available amount in minor units (credits_posted - debits_posted - debits_pending).
	//
	// Example: 9800
	Available AvailableBalance `json:"available"`
	Balances  AccountBalances  `json:"balances"`
	ClosedAt  *time.Time       `json:"closed_at"`
	CreatedAt time.Time        `json:"created_at"`

	// HolderReference Stable opaque reference assigned to a holder by the ledger.
	//
	// Example: hld_01K33YVADP5Z8B0T3X2Q91C6RH
	HolderReference HolderReference `json:"holder_reference"`

	// Kind Example: payable
	Kind PayableAccountKind `json:"kind"`

	// LedgerSlug Opaque identifier assigned to the ledger.
	//
	// Example: ngn_ng
	LedgerSlug LedgerSlug `json:"ledger_slug"`

	// Name Example: Acme Ltd
	Name string `json:"name"`

	// Reference Stable opaque reference assigned to an account by the ledger.
	//
	// Example: acct_01K33YV8M82N9MXP4E7J6B1QWK
	Reference AccountReference `json:"reference"`

	// Status Whether the payable account itself is open or closed.
	//
	// Example: open
	Status AccountStatus `json:"status"`
}

// GetAccountStatementResponse defines model for GetAccountStatementResponse.
type GetAccountStatementResponse struct {
	Account StatementAccount `json:"account"`

	// ClosingBalance Posted balance at the end of the requested period in minor units.
	//
	// Example: 9600
	ClosingBalance int64               `json:"closing_balance"`
	Entries        []StatementMovement `json:"entries"`

	// OpeningBalance Posted balance before the requested period in minor units.
	//
	// Example: 0
	OpeningBalance int64           `json:"opening_balance"`
	Page           StatementPage   `json:"page"`
	Period         StatementPeriod `json:"period"`
}

// HealthResponse defines model for HealthResponse.
type HealthResponse struct {
	// Status Example: ok
	Status string `json:"status"`
}

// HolderReference Stable opaque reference assigned to a holder by the ledger.
//
// Example: hld_01K33YVADP5Z8B0T3X2Q91C6RH
type HolderReference = string

// IdempotencyKey Caller-generated identifier used to make a ledger operation idempotent.
//
// Example: payment_123
type IdempotencyKey = string

// JournalEntryKind Business classification of a journal entry.
type JournalEntryKind = string

// JournalRef Stable opaque reference assigned to a journal entry by the ledger.
//
// Example: jrn_01K33YW0MDHJ9E4N7Z2QPV6R8K
type JournalRef = string

// LedgerSlug Opaque identifier assigned to the ledger.
//
// Example: ngn_ng
type LedgerSlug = string

// PayableAccountKind Example: payable
type PayableAccountKind string

// PostJournalEntryLine defines model for PostJournalEntryLine.
type PostJournalEntryLine struct {
	// Amount Positive amount expressed in the ledger's minor units.
	//
	// Example: 10000
	Amount int64 `json:"amount"`

	// CreditAccountRef Stable opaque reference assigned to an account by the ledger.
	//
	// Example: acct_01K33YV8M82N9MXP4E7J6B1QWK
	CreditAccountRef AccountReference `json:"credit_account_ref"`

	// DebitAccountRef Stable opaque reference assigned to an account by the ledger.
	//
	// Example: acct_01K33YV8M82N9MXP4E7J6B1QWK
	DebitAccountRef AccountReference `json:"debit_account_ref"`

	// Purpose What this line's amount is for within the entry, such as a fee or tax. Client-defined.
	Purpose string `json:"purpose"`
}

// PostJournalEntryRequest defines model for PostJournalEntryRequest.
type PostJournalEntryRequest struct {
	Description string     `json:"description"`
	EffectiveAt *time.Time `json:"effective_at,omitempty"`

	// Kind Business classification of a journal entry.
	Kind JournalEntryKind `json:"kind"`

	// Ledger Opaque identifier assigned to the ledger.
	//
	// Example: ngn_ng
	Ledger LedgerSlug             `json:"ledger"`
	Lines  []PostJournalEntryLine `json:"lines"`
}

// PostJournalEntryResponse defines model for PostJournalEntryResponse.
type PostJournalEntryResponse struct {
	CreatedAt   time.Time `json:"created_at"`
	Description string    `json:"description"`
	EffectiveAt time.Time `json:"effective_at"`

	// JournalRef Stable opaque reference assigned to a journal entry by the ledger.
	//
	// Example: jrn_01K33YW0MDHJ9E4N7Z2QPV6R8K
	JournalRef JournalRef `json:"journal_ref"`

	// Kind Business classification of a journal entry.
	Kind JournalEntryKind `json:"kind"`

	// LedgerSlug Opaque identifier assigned to the ledger.
	//
	// Example: ngn_ng
	LedgerSlug LedgerSlug                    `json:"ledger_slug"`
	State      PostJournalEntryResponseState `json:"state"`
}

// PostJournalEntryResponseState defines model for PostJournalEntryResponse.State.
type PostJournalEntryResponseState string

// StatementAccount defines model for StatementAccount.
type StatementAccount struct {
	// HolderReference Stable opaque reference assigned to a holder by the ledger.
	//
	// Example: hld_01K33YVADP5Z8B0T3X2Q91C6RH
	HolderReference HolderReference `json:"holder_reference"`

	// Name Example: Acme Ltd
	Name string `json:"name"`

	// Reference Stable opaque reference assigned to an account by the ledger.
	//
	// Example: acct_01K33YV8M82N9MXP4E7J6B1QWK
	Reference AccountReference `json:"reference"`
}

// StatementDirection Example: credit
type StatementDirection string

// StatementMovement defines model for StatementMovement.
type StatementMovement struct {
	// Amount Positive amount expressed in the ledger's minor units.
	//
	// Example: 9800
	Amount int64 `json:"amount"`

	// BalanceAfter Posted balance after this movement in minor units.
	//
	// Example: 9800
	BalanceAfter int64 `json:"balance_after"`

	// Description Example: Payment received
	Description string `json:"description"`

	// Direction Example: credit
	Direction StatementDirection `json:"direction"`

	// JournalReference Stable opaque reference assigned to a journal entry by the ledger.
	//
	// Example: jrn_01K33YW0MDHJ9E4N7Z2QPV6R8K
	JournalReference JournalRef `json:"journal_reference"`

	// Kind Business classification of a journal entry.
	Kind JournalEntryKind `json:"kind"`

	// LineNumber Example: 1
	LineNumber int `json:"line_number"`

	// Purpose Example: Card payment
	Purpose string `json:"purpose"`

	// RecordedAt Example: 2026-09-10T09:15:00Z
	RecordedAt time.Time `json:"recorded_at"`
}

// StatementPage defines model for StatementPage.
type StatementPage struct {
	// Limit Example: 50
	Limit int `json:"limit"`

	// NextCursor Example: eyJ...
	NextCursor     *string `json:"next_cursor"`
	PreviousCursor *string `json:"previous_cursor"`
}

// StatementPeriod defines model for StatementPeriod.
type StatementPeriod struct {
	// From Example: 2026-09-01T00:00:00Z
	From time.Time `json:"from"`

	// To Example: 2026-10-01T00:00:00Z
	To time.Time `json:"to"`
}

// ValidationError defines model for ValidationError.
type ValidationError struct {
	Code    ValidationErrorCode     `json:"code"`
	Details []ValidationErrorDetail `json:"details"`
}

// ValidationErrorCode defines model for ValidationError.Code.
type ValidationErrorCode string

// ValidationErrorDetail defines model for ValidationErrorDetail.
type ValidationErrorDetail struct {
	Code ValidationErrorDetailCode `json:"code"`

	// Field Example: external_id
	Field    string                        `json:"field"`
	Location ValidationErrorDetailLocation `json:"location"`

	// Message Example: external_id is required
	Message string `json:"message"`
}

// ValidationErrorDetailCode defines model for ValidationErrorDetail.Code.
type ValidationErrorDetailCode string

// ValidationErrorDetailLocation defines model for ValidationErrorDetail.Location.
type ValidationErrorDetailLocation string

// ValidationErrorResponse defines model for ValidationErrorResponse.
type ValidationErrorResponse struct {
	Error ValidationError `json:"error"`

	// Message Example: Request validation failed.
	Message string `json:"message"`
}

// InvalidRequest defines model for InvalidRequest.
type InvalidRequest = ValidationErrorResponse

// GetAccountStatementParams defines parameters for GetAccountStatement.
type GetAccountStatementParams struct {
	// From Inclusive recorded-time boundary.
	From *time.Time `form:"from,omitempty" json:"from,omitempty"`

	// To Exclusive recorded-time boundary.
	To *time.Time `form:"to,omitempty" json:"to,omitempty"`

	// Limit Bounded number of movements to return.
	Limit *int `form:"limit,omitempty" json:"limit,omitempty"`

	// Cursor Opaque token returned by a preceding request.
	Cursor *string `form:"cursor,omitempty" json:"cursor,omitempty"`
}

// PostJournalEntryParams defines parameters for PostJournalEntry.
type PostJournalEntryParams struct {
	// IdempotencyKey Caller-generated key that uniquely identifies this posting within the ledger.
	IdempotencyKey IdempotencyKey `json:"Idempotency-Key"`
}

// CreatePayableAccountJSONRequestBody defines body for CreatePayableAccount for application/json ContentType.
type CreatePayableAccountJSONRequestBody = CreatePayableAccountRequest

// PostJournalEntryJSONRequestBody defines body for PostJournalEntry for application/json ContentType.
type PostJournalEntryJSONRequestBody = PostJournalEntryRequest

// PostJournalEntriesBatchJSONRequestBody defines body for PostJournalEntriesBatch for application/json ContentType.
type PostJournalEntriesBatchJSONRequestBody = BatchPostEntriesRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// CreatePayableAccount Create a payable account in a ledger
	// (POST /accounts)
	CreatePayableAccount(w http.ResponseWriter, r *http.Request)
	// GetAccount Get a payable account and its balance
	// (GET /accounts/{account_reference})
	GetAccount(w http.ResponseWriter, r *http.Request, accountReference AccountReference)
	// GetAccountStatement Get a payable account statement
	// (GET /accounts/{account_reference}/statement)
	GetAccountStatement(w http.ResponseWriter, r *http.Request, accountReference AccountReference, params GetAccountStatementParams)
	// PostJournalEntry Post a journal entry to a ledger
	// (POST /entries)
	PostJournalEntry(w http.ResponseWriter, r *http.Request, params PostJournalEntryParams)
	// PostJournalEntriesBatch Post a batch of journal entries to a ledger
	// (POST /entries/batch)
	PostJournalEntriesBatch(w http.ResponseWriter, r *http.Request)
	// GetHealth Check whether the service is running
	// (GET /health)
	GetHealth(w http.ResponseWriter, r *http.Request)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// CreatePayableAccount operation middleware
func (siw *ServerInterfaceWrapper) CreatePayableAccount(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreatePayableAccount(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetAccount operation middleware
func (siw *ServerInterfaceWrapper) GetAccount(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "account_reference" -------------
	var accountReference AccountReference

	err = runtime.BindStyledParameterWithOptions("simple", "account_reference", r.PathValue("account_reference"), &accountReference, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "account_reference", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetAccount(w, r, accountReference)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetAccountStatement operation middleware
func (siw *ServerInterfaceWrapper) GetAccountStatement(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "account_reference" -------------
	var accountReference AccountReference

	err = runtime.BindStyledParameterWithOptions("simple", "account_reference", r.PathValue("account_reference"), &accountReference, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "account_reference", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params GetAccountStatementParams

	// ------------- Optional query parameter "from" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "from", r.URL.Query(), &params.From, runtime.BindQueryParameterOptions{Type: "string", Format: "date-time"})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "from"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "from", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "to" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "to", r.URL.Query(), &params.To, runtime.BindQueryParameterOptions{Type: "string", Format: "date-time"})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "to"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "to", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", r.URL.Query(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "limit"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "cursor" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "cursor", r.URL.Query(), &params.Cursor, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "cursor"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "cursor", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetAccountStatement(w, r, accountReference, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostJournalEntry operation middleware
func (siw *ServerInterfaceWrapper) PostJournalEntry(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params PostJournalEntryParams

	headers := r.Header

	// ------------- Required header parameter "Idempotency-Key" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("Idempotency-Key")]; found {
		var IdempotencyKey IdempotencyKey
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "Idempotency-Key", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "Idempotency-Key", valueList[0], &IdempotencyKey, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true, Type: "string", Format: ""})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "Idempotency-Key", Err: err})
			return
		}

		params.IdempotencyKey = IdempotencyKey

	} else {
		err := fmt.Errorf("Header parameter Idempotency-Key is required, but not found")
		siw.ErrorHandlerFunc(w, r, &RequiredHeaderError{ParamName: "Idempotency-Key", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostJournalEntry(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostJournalEntriesBatch operation middleware
func (siw *ServerInterfaceWrapper) PostJournalEntriesBatch(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostJournalEntriesBatch(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetHealth operation middleware
func (siw *ServerInterfaceWrapper) GetHealth(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetHealth(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

// ServeMux is an abstraction of [http.ServeMux].
type ServeMux interface {
	HandleFunc(pattern string, handler func(http.ResponseWriter, *http.Request))
	http.Handler
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/health", wrapper.GetHealth)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/accounts", wrapper.CreatePayableAccount)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/accounts/{account_reference}", wrapper.GetAccount)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/accounts/{account_reference}/statement", wrapper.GetAccountStatement)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/entries", wrapper.PostJournalEntry)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/entries/batch", wrapper.PostJournalEntriesBatch)

	return m
}

type InvalidRequestJSONResponse ValidationErrorResponse

type CreatePayableAccountRequestObject struct {
	Body *CreatePayableAccountJSONRequestBody
}

type CreatePayableAccountResponseObject interface {
	VisitCreatePayableAccountResponse(w http.ResponseWriter) error
}

type CreatePayableAccount200JSONResponse CreatePayableAccountResponse

func (response CreatePayableAccount200JSONResponse) VisitCreatePayableAccountResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type CreatePayableAccount201JSONResponse CreatePayableAccountResponse

func (response CreatePayableAccount201JSONResponse) VisitCreatePayableAccountResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)
	_, err := buf.WriteTo(w)
	return err
}

type CreatePayableAccount400JSONResponse struct{ InvalidRequestJSONResponse }

func (response CreatePayableAccount400JSONResponse) VisitCreatePayableAccountResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type CreatePayableAccount409JSONResponse ErrorResponse

func (response CreatePayableAccount409JSONResponse) VisitCreatePayableAccountResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(409)
	_, err := buf.WriteTo(w)
	return err
}

type CreatePayableAccount500JSONResponse ErrorResponse

func (response CreatePayableAccount500JSONResponse) VisitCreatePayableAccountResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type GetAccountRequestObject struct {
	AccountReference AccountReference `json:"account_reference"`
}

type GetAccountResponseObject interface {
	VisitGetAccountResponse(w http.ResponseWriter) error
}

type GetAccount200JSONResponse GetAccountResponse

func (response GetAccount200JSONResponse) VisitGetAccountResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetAccount400JSONResponse struct{ InvalidRequestJSONResponse }

func (response GetAccount400JSONResponse) VisitGetAccountResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type GetAccount404JSONResponse ErrorResponse

func (response GetAccount404JSONResponse) VisitGetAccountResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type GetAccount500JSONResponse ErrorResponse

func (response GetAccount500JSONResponse) VisitGetAccountResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type GetAccountStatementRequestObject struct {
	AccountReference AccountReference `json:"account_reference"`
	Params           GetAccountStatementParams
}

type GetAccountStatementResponseObject interface {
	VisitGetAccountStatementResponse(w http.ResponseWriter) error
}

type GetAccountStatement200JSONResponse GetAccountStatementResponse

func (response GetAccountStatement200JSONResponse) VisitGetAccountStatementResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetAccountStatement400JSONResponse struct{ InvalidRequestJSONResponse }

func (response GetAccountStatement400JSONResponse) VisitGetAccountStatementResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type GetAccountStatement404JSONResponse ErrorResponse

func (response GetAccountStatement404JSONResponse) VisitGetAccountStatementResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type GetAccountStatement500JSONResponse ErrorResponse

func (response GetAccountStatement500JSONResponse) VisitGetAccountStatementResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type PostJournalEntryRequestObject struct {
	Params PostJournalEntryParams
	Body   *PostJournalEntryJSONRequestBody
}

type PostJournalEntryResponseObject interface {
	VisitPostJournalEntryResponse(w http.ResponseWriter) error
}

type PostJournalEntry200JSONResponse PostJournalEntryResponse

func (response PostJournalEntry200JSONResponse) VisitPostJournalEntryResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type PostJournalEntry201JSONResponse PostJournalEntryResponse

func (response PostJournalEntry201JSONResponse) VisitPostJournalEntryResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)
	_, err := buf.WriteTo(w)
	return err
}

type PostJournalEntry400JSONResponse struct{ InvalidRequestJSONResponse }

func (response PostJournalEntry400JSONResponse) VisitPostJournalEntryResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type PostJournalEntry404JSONResponse ErrorResponse

func (response PostJournalEntry404JSONResponse) VisitPostJournalEntryResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type PostJournalEntry409JSONResponse ErrorResponse

func (response PostJournalEntry409JSONResponse) VisitPostJournalEntryResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(409)
	_, err := buf.WriteTo(w)
	return err
}

type PostJournalEntry500JSONResponse ErrorResponse

func (response PostJournalEntry500JSONResponse) VisitPostJournalEntryResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type PostJournalEntriesBatchRequestObject struct {
	Body *PostJournalEntriesBatchJSONRequestBody
}

type PostJournalEntriesBatchResponseObject interface {
	VisitPostJournalEntriesBatchResponse(w http.ResponseWriter) error
}

type PostJournalEntriesBatch200JSONResponse BatchPostEntriesResponse

func (response PostJournalEntriesBatch200JSONResponse) VisitPostJournalEntriesBatchResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type PostJournalEntriesBatch400JSONResponse struct{ InvalidRequestJSONResponse }

func (response PostJournalEntriesBatch400JSONResponse) VisitPostJournalEntriesBatchResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type PostJournalEntriesBatch404JSONResponse ErrorResponse

func (response PostJournalEntriesBatch404JSONResponse) VisitPostJournalEntriesBatchResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type PostJournalEntriesBatch409JSONResponse ErrorResponse

func (response PostJournalEntriesBatch409JSONResponse) VisitPostJournalEntriesBatchResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(409)
	_, err := buf.WriteTo(w)
	return err
}

type PostJournalEntriesBatch500JSONResponse ErrorResponse

func (response PostJournalEntriesBatch500JSONResponse) VisitPostJournalEntriesBatchResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type GetHealthRequestObject struct {
}

type GetHealthResponseObject interface {
	VisitGetHealthResponse(w http.ResponseWriter) error
}

type GetHealth200JSONResponse HealthResponse

func (response GetHealth200JSONResponse) VisitGetHealthResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// CreatePayableAccount Create a payable account in a ledger
	// (POST /accounts)
	CreatePayableAccount(ctx context.Context, request CreatePayableAccountRequestObject) (CreatePayableAccountResponseObject, error)
	// GetAccount Get a payable account and its balance
	// (GET /accounts/{account_reference})
	GetAccount(ctx context.Context, request GetAccountRequestObject) (GetAccountResponseObject, error)
	// GetAccountStatement Get a payable account statement
	// (GET /accounts/{account_reference}/statement)
	GetAccountStatement(ctx context.Context, request GetAccountStatementRequestObject) (GetAccountStatementResponseObject, error)
	// PostJournalEntry Post a journal entry to a ledger
	// (POST /entries)
	PostJournalEntry(ctx context.Context, request PostJournalEntryRequestObject) (PostJournalEntryResponseObject, error)
	// PostJournalEntriesBatch Post a batch of journal entries to a ledger
	// (POST /entries/batch)
	PostJournalEntriesBatch(ctx context.Context, request PostJournalEntriesBatchRequestObject) (PostJournalEntriesBatchResponseObject, error)
	// GetHealth Check whether the service is running
	// (GET /health)
	GetHealth(ctx context.Context, request GetHealthRequestObject) (GetHealthResponseObject, error)
}

type StrictHandlerFunc func(ctx context.Context, w http.ResponseWriter, r *http.Request, request any) (any, error)
type StrictMiddlewareFunc func(f StrictHandlerFunc, operationID string) StrictHandlerFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	if options.RequestErrorHandlerFunc == nil {
		options.RequestErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	if options.ResponseErrorHandlerFunc == nil {
		options.ResponseErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		}
	}
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// CreatePayableAccount operation middleware
func (sh *strictHandler) CreatePayableAccount(w http.ResponseWriter, r *http.Request) {
	var request CreatePayableAccountRequestObject

	var body CreatePayableAccountJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.CreatePayableAccount(ctx, request.(CreatePayableAccountRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreatePayableAccount")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(CreatePayableAccountResponseObject); ok {
		if err := validResponse.VisitCreatePayableAccountResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetAccount operation middleware
func (sh *strictHandler) GetAccount(w http.ResponseWriter, r *http.Request, accountReference AccountReference) {
	var request GetAccountRequestObject

	request.AccountReference = accountReference

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetAccount(ctx, request.(GetAccountRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetAccount")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetAccountResponseObject); ok {
		if err := validResponse.VisitGetAccountResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetAccountStatement operation middleware
func (sh *strictHandler) GetAccountStatement(w http.ResponseWriter, r *http.Request, accountReference AccountReference, params GetAccountStatementParams) {
	var request GetAccountStatementRequestObject

	request.AccountReference = accountReference
	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetAccountStatement(ctx, request.(GetAccountStatementRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetAccountStatement")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetAccountStatementResponseObject); ok {
		if err := validResponse.VisitGetAccountStatementResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// PostJournalEntry operation middleware
func (sh *strictHandler) PostJournalEntry(w http.ResponseWriter, r *http.Request, params PostJournalEntryParams) {
	var request PostJournalEntryRequestObject

	request.Params = params

	var body PostJournalEntryJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.PostJournalEntry(ctx, request.(PostJournalEntryRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PostJournalEntry")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(PostJournalEntryResponseObject); ok {
		if err := validResponse.VisitPostJournalEntryResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// PostJournalEntriesBatch operation middleware
func (sh *strictHandler) PostJournalEntriesBatch(w http.ResponseWriter, r *http.Request) {
	var request PostJournalEntriesBatchRequestObject

	var body PostJournalEntriesBatchJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.PostJournalEntriesBatch(ctx, request.(PostJournalEntriesBatchRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PostJournalEntriesBatch")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(PostJournalEntriesBatchResponseObject); ok {
		if err := validResponse.VisitPostJournalEntriesBatchResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetHealth operation middleware
func (sh *strictHandler) GetHealth(w http.ResponseWriter, r *http.Request) {
	var request GetHealthRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetHealth(ctx, request.(GetHealthRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetHealth")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetHealthResponseObject); ok {
		if err := validResponse.VisitGetHealthResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"7Fx7c9u2sv8qO+yZOW2vLFPyI7b6x53EThrn0TqOJ+1NmitD5MpCTQEqADrWif3d7+BBEnxIohQ7vXNO",
	"/kkskgAWi33htwt8DiI+nXGGTMlg8DkQKGecSTQ/Ttg1SWh8hn+lKJV+EnGmkJk/yWyW0Igoytn2n5Iz",
	"/UxGE5wS/dc/BI6DQfDddtH9tn0rt9/pTk3Dp0JwceaGDO7u7jpBjDISdKbfBoPgfIIg7PAQc5TAuAJJ",
	"FJXjOagJwuPTE9BECRKpbqA7cKNoIh5HEU+ZekISwiI7JRLHVPdNklPBZygU1c/HJJHYCWbeo89BJDCm",
	"Sg5nyGLKLvWjCnFckQTca7CfA5nqIYEymFLGBaSMKtkNOgHekOkswWAQdoIxF1OigkFAmdrfDTrBlDI6",
	"TafmpZrP0L7CSxTBXaeghEuF8UJCzNv2dPTCMFyflhhHazDFfN2Clv4XUNKGKW3pWJeKu06gxZMKTcGH",
	"KnM6NRmqUl1b24/5GHz0J0ZKT9SJ8RmOUSCLsD7Xt4qMEgQ+I3+lWmHch0CkpJcMY1AcCANiO4KR1Z0E",
	"40sUpfkHJIrUMOy93Nn5n3cHrw/6vxy+/v109+mjF/tPem9+e6nZQW5eIbtUk2Cwv2u4k/3s5bRLJexs",
	"b7auc2XfmqKU5NIql9dLME2lMoqNNxFiDPu7EE2I1mgUMigNUXw7QsDpTM3NGjgOvVVEpbLOnt8mqCYo",
	"zKRnZG54lfGCKonJGKgEPkMGXECUcImxYQvTy/4h0G/0UpkXeokKfrlX5Xlriq4JTfRAzvjUiTpGQa8x",
	"BpJ92Sye8H1ZQmALSiLk/bYy9kNpQQ8PNtCsJ0RFk6dMibkx0OvaTR7jKhdg+j3SH951AicXuk2FjxX1",
	"Mj0X3zfpiiH9lEulyacoPd9VphLt+wZdQqW06UpnQGCku4OISyWBjHiq4NOEKFDIQFJ2maAxMJRdSvNR",
	"ByQHAnJKkgSFa00lyIR/MvJHWNbACKMkUwRHidbR7exvzhCIAgKKTrELb5HFMMa8Dz2+lmgEyqRCYqSV",
	"KpzKVYwv8Wd+onBqVoDcnNjWPeMTppTlv3MmEyHIfIVOu1aFmmrfTLREc4GWdj1CNufAH8o2yhoQBQkS",
	"qaCXf/2T4V2JD2YxPL45dhQaafocobF+hn4tU9bwrWLVK/PV2yStC6LroJNLUTtRdHHOeuokUKaJDc42",
	"WOEz01qTU1rF6oSyQVbOw4pMTZtKKlSy7ntOnjwnMSNKodC61v3xjz/edn8M7slx7IXhOp7Dp8R/O0oI",
	"u2oQIfDMEo7HGCl6jUNijEtuYWOicEtrbZNXoDFOZ1whi+bDK5wbSUiSX8fB4MPyRT0pGr7EeXD3sRoo",
	"n8TIFB0bOzKh0qjMvGNmpIoYemB+mHfaLOkf2slYPaISBGpJjYGwuPIy4lOUMCLRFRAJF3hDjRW76MKJ",
	"AjkhwhmtK5zLGYkQZihcgAGfqJqY7q5wDhKZUdmL01/fnueKe2EsZ24S9YdqInh6OQGkxncji2ecMgWM",
	"TFGWree8q5l7RVm8Sjle8FQwkhhJfqm/19aAMmyvXloR/F5eUYY1E1qyoA9gQOFPSwFY2ltYUb02fqOl",
	"FrJiHKpS61hdFsGMj6stiDNJ61lBzAORVvpSjWC0wrA0MXFWMFAixWZtXEcHO4Fj6NA0akuaE54zHDdT",
	"JfMgNgs/I4HEbhYytQv0AmnulnYMC6Km+vK5IcoT6DgeNy3gkaHg1IbO+XZkUWR1o20qSYY0rhjs/t7e",
	"Zr7gkm9ptQ8GwVPX+cnxpk6iv7f3tZzE+nFGJ7DzvB+2/X/mzsKIypMex432ErlRgJVvwFYtVG1Pd9cJ",
	"Rh62tLRtBYq6y7aTy+KHsm1oiCecZVgrBqmoZ7GVnaKIJoSpYa+/E6ze2Dfq5F0nmPAkRjEUPlqxjDPP",
	"zfcFuNHSk5eXPvflRoyGUivTRmpXsONxNEV4peIVrDBy3HKqNSCnZO5btHQAR1V5aiz3aSozpVHBcoee",
	"O4ZCNjuefnjiXpK9JgUtdvieJ3OUMK6GY56aId0jh63k4hNxNk5oZMa3cy+1yp7lzSiT6XhMI4pMDccp",
	"izWJvufzOqTMcUCiuEYxrPq9YmXNJE7YmD8sBNIEcyzk6YZWLg+gVtJk5luGZZYqQIX6rNmyeOJnVOva",
	"7FwxSwbbwlu+Ea6h9mEdP3fIdxXK7vsP3adh2VBri1w2u0E/7O9vhYdb4cF5LxzshIMwfB80mcFgksQZ",
	"tPr4+HTv/cGT8Hzn9/6bw97R/tnzTAsHgYMoK5o7CNglGxrj6+yuZ6H8YVZDuJnNsejl3X+4Q/zmsL66",
	"w/K9U4PzKjss55ucp7pHF1VYIU0mTnHzENJ2s4op+TBu2EzoKbscjhblCU4tzO/e6x29xXBi4GMf28EY",
	"Zigoj5fltw73G9MB9RSAB4+3gkXyqb3m1+b/OuTYMeZmnbmOcGxRj/Um2W6GM+fbWs3qVH+sG5nB2zez",
	"n1fFPxOXvL86a+qCUayJo71JpJ8jSdRkQyn2kIciv3UVrHL4rlkjORVTuVniEqyJWJa2XOla18ha3nWC",
	"CtRTI/vI5He2LpGh0BYGaAa/CkilJXtKrvSG12Ggms9mJw55UKrKU5iRuRaZbPf1b7797wQ1KLbG5Sep",
	"pAylhCjR8jB21Sba7pEczHT474oVfjCGrZervgd+nVmscRM1KrFsmTb9KZjTpt/C18fPXxw+3f3l0fv+",
	"m9N3+2cHL9fWJi9wqVH+qyXZ0x+f5kUE5pGwT8hOiZAdn9f/+4Fs/SvcOvz4X9//92CY//jhx3/cmxzs",
	"rJCDGiJfaVARjOxzkziOiNR80B9Ik5th6XSk/5Y4I9YAjeZZQjplMQoZcWE8xTKJaohIvb16tgv5WDFS",
	"LsyqrXJjYqQGDtsah0bPTxW9zosg8GYmUGpTSpknBv+U65czkRtb6nDY7+/sPOqHO/sHe7uPHu1nmW77",
	"tleLEZZLgm1VkwNNqnsLMp3NuNCr42btDZevyKWJUV0++18oeGNmxi84srvZYQaBuOTDumG82ed+aSez",
	"VMy4xKaKGxOnUmmSTf+UeW2LhDG3GUG3ri5RKdNoAkQCgTEicAGK3HThKKHI1FaMY8psSY6ng72vmFnu",
	"fa3MclNBWWmVGte/E+QSli1JUzhWVdGFKZxv6fxWyMHGGecN8kLfstQrstR5BmnN5HRdKTbaPG2CPFXV",
	"bHkYtZmMVnLUbTPTXyrcGyBaeh9ZyhbUSmIXbEDLWexG8Mj2XRWKEkdXwkU19GY9AbkHmPFvwvzWA+8W",
	"pmxz/h1TodluhT5bbOPpcu9Wjjrds4ZZ1WGnNYG7BwtHVxXe9powKYf1DMlYWf+wHAoc28CRSpi66S/F",
	"/g5aYn8Vs1Ssw6mFKEBghPQaW0hd7C91K8isEI6y8WonvPdkwijDod1jlRjQW7V+XjxccO2IiBgcutNG",
	"TyMu4tyRFN1keaZeeB4eDnp7Ls/UxgsstpcF5O5NuXCh+Vp4AWZZRqsmNeNAeSJLzcGpA2LXUNuETmmZ",
	"PXuht9PrrdjZaVOKN2oYpULy8hIHOH/R7Xbb5JpmAq8pT6XXzYo21YjFzKLeUZm65bzL8eg1uDcWfNos",
	"W2HvPAwHYbiGbHUCxRs664WbdFZhkCHUDNDEhMoxsg1T9Jn/KYLdJfUAMSpCk/ZheIXEY9PcxOELA+8F",
	"Zx6ykVswwo3yZezISegE1J4CHJpxi59uPYsH1yRJ0Rq4YWItnNHJ4kfKrhj/xIZjikncyGD7pqyQpXqV",
	"FdYz4RYjrk5F73LN/lCT8VeKQu9wJkhiY8JGPJ43kuOVQDQSZGumc06tUyaRU5pNutPmeMuio5MPUAtS",
	"Va9F7HAgAhQKBGNCEwfX3GvhiG5BXTVOOTJ6fn5+as6Cjrnw4jOQKK5phJoURZWh12469MdBJ7hGIW0P",
	"YbfXDbMkJZnRYBDsdMPujhMbw7dth7mYH3p3ov/PMzsnsXb2DXWJQSeTwSda0O7rGO2yotzK7tiVFpcO",
	"9/bD8IFJWXys9zFziH9Ekvx87yciIXOFyRz0MAkqjH+yOKErfS4O7pnjCqkwwOBdJ+iHvb9tPucNBwv1",
	"dNyO0tC3a/ndNGy+LtuVE9em2WGLaTl19DaaR1m9m550Op0SMXeEumyqXQClGW2/lPagBmEFr+2nWk+M",
	"bfdNh3UYtXI930q49C9oldW+QpuGlYN1vcrpI1vdV5uBU24qIa//W0hgub6wRN6rSjddu7TtRGSto+uV",
	"WZc2kFEqhN5UGYjCSMpeK830CuKqc24ucCzNXVNn30LE0yR2KJ5VOb/iwlB0jyxpO6geNV90q49A6qd3",
	"WZ5iN01yC7392cPH7S7nTtN/iQ27/TNz7OnaHWGqjkFYrPf/XKKEEVcToEpCvOj0rv5af2DScMlcC7YT",
	"V9MbCtmFc71l194qv9LA9g/ZwkFE5AS4AIHXyNKcFrOhLzucoojJeCpBpmjQ8sGHzwFlJmVngh5XM1jj",
	"SlD1E21XuwEn+viALqahZHQNQ2zqhs3aZD7DaqJeqaxg7Mus9O6XqWy9yLmkrm7qRlbM6/tWS6++qsI+",
	"T0apMwffDFTVQP2MqsE6ZbYgK+FaaaG2Zbaxb2GrNDlZsiTD/yQQi2mzy0Zb5hKvBDJ0xmzEXU1dJwM3",
	"9RsTRs/hEwoEs7pFRUbW2fcXHsbTAalZwyK8+KH7B/uDfffdd/DUikBBnn5xC2euGRAFt+AQOK9s5RZe",
	"UhbDLeRgINzCY2tfb8GVDMOt7mprawsW/DvI/9MfFvAZGPgMbuHC1rm87ocvem+O+78/OXj56OfdXw6P",
	"3j3bP995fAG3GWwHt3Bkr1W5hcPOQRgW/99H38fmdhLdj+1433a8xNbnANDfb/Q7VQk9YVGSSnqNFSEb",
	"abtFbLGWITLbhzsqHdpTENIOMaoO//Rms+EVv4fBn+hBMCvQAT72NFNx53wWUZDhgQURMY6JOSu7HrxZ",
	"p8uVWSl+haxwgaO5NloCIzSX9eS2rZm8HJ0s6KvyY7MAwD/aUaTWFh6geN0Pnz/6/eXu48M3/fP3B+9+",
	"3n/y7HSnd9b2YIRuf/Ao3H3We3b8unf07Le374/fvTh911iNbQum82roD0XKqHT0JMvY2IeVrE09a+Kl",
	"RYrkVkOyI1huRUpHRpw1KOUuel5KopqHKCUamrMLWo6y6fabZru/9myzNN8DTLbvT/ZU8AilXksYI7ac",
	"7seGEvWwqBR3WQeti6X0QWDrLof+w4b0AEuTpFRCbnH4ReC74ouw9Pab1GUnHFpGz3lEYuJomUaareM0",
	"SebutojrL8U3vkXO3yLnhVJnY2bvNEoz7Fot4qmHRSsK+O2NI0RByuhfKSbzoiTZ3aiS3dvk1S4WpcnG",
	"X+b5BOeGvFMEWy/NxQubBV3Viyesm71/QHlReeBXBpMXFmTdM5CcX4PzYDDyOjM593ZzljIzDVPx8R9r",
	"Xx8Xm8J4gVmFii5uBJm7rpvw5kYSWiHPlTPqjVwrYc+lA+uL8XvvI2O2KuJuzh+NuYCYjg3hts7SBkwL",
	"iW08Kl8i+aTFsAZTq43r5uad0H9mDuiX+exdT+k2+AL1xsLu/z8ZpzJCVxu8nPMNlwGUp+K9B/P+3yrr",
	"kHmqStYhN3xZbvRbwmFhVKItd+3ElDlE5ScbXFiybe559IOTCiJBoonrIiLC3lOoJPBPrKbLzpiNeDzv",
	"gCDu1lLCfFpNJ/MM4aMMCIOLSqxxATYYMZe1lW9aM/ZzkN9tqbfZEqaE6cFjnCHT/tRF9zYocy07Bs8k",
	"Wc8RYcBZMgcZ8Rlm2GDGT5vjyC9tU+TKGO2FhNrO9YTMBXF5miybM5VALxkXGBtwUS+su10zv7/VXIhp",
	"DgzrVS6OWf5kuJ3dEEkEduEMpbugmPgBRHFfJxljx0sX+Dfe2QMsE6LQitV0SpVyd+ZduITvRV6HIByg",
	"sjRcpSjNhWUPVCiw6E7UrxzXLbwPs0Fxzbcws5t4jLvwa6rsFYSasVgoVI5lUZbLioGv/9aYqXbPTZMH",
	"eLAdqbPvDdvPtSKjL/drDzGrcv/fPNcCz2VNGR+XXJi7ZbjsxCbmygAv31TLOdhLBYIHNA2VawuW8ING",
	"qEXAEj2v1QlMMLqCT951314bkTLmDtnd/V8AAAD//w==",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
