//go:build go1.22

// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/flate"
	"context"
	"encoding/base64"
	"encoding/json"
	"errors"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/oapi-codegen/runtime"
)

// Defines values for AccountStatus.
const (
	Closed AccountStatus = "closed"
	Open   AccountStatus = "open"
)

// Valid indicates whether the value is a known member of the AccountStatus enum.
func (e AccountStatus) Valid() bool {
	switch e {
	case Closed:
		return true
	case Open:
		return true
	default:
		return false
	}
}

// Defines values for ErrorCode.
const (
	AccountClosed       ErrorCode = "account_closed"
	AccountNotFound     ErrorCode = "account_not_found"
	HolderConflict      ErrorCode = "holder_conflict"
	IdempotencyConflict ErrorCode = "idempotency_conflict"
	InsufficientFunds   ErrorCode = "insufficient_funds"
	InternalServerError ErrorCode = "internal_server_error"
	LedgerClosed        ErrorCode = "ledger_closed"
)

// Valid indicates whether the value is a known member of the ErrorCode enum.
func (e ErrorCode) Valid() bool {
	switch e {
	case AccountClosed:
		return true
	case AccountNotFound:
		return true
	case HolderConflict:
		return true
	case IdempotencyConflict:
		return true
	case InsufficientFunds:
		return true
	case InternalServerError:
		return true
	case LedgerClosed:
		return true
	default:
		return false
	}
}

// Defines values for PayableAccountKind.
const (
	Payable PayableAccountKind = "payable"
)

// Valid indicates whether the value is a known member of the PayableAccountKind enum.
func (e PayableAccountKind) Valid() bool {
	switch e {
	case Payable:
		return true
	default:
		return false
	}
}

// Defines values for PostJournalEntryResponseState.
const (
	Posted PostJournalEntryResponseState = "posted"
)

// Valid indicates whether the value is a known member of the PostJournalEntryResponseState enum.
func (e PostJournalEntryResponseState) Valid() bool {
	switch e {
	case Posted:
		return true
	default:
		return false
	}
}

// Defines values for StatementDirection.
const (
	Credit StatementDirection = "credit"
	Debit  StatementDirection = "debit"
)

// Valid indicates whether the value is a known member of the StatementDirection enum.
func (e StatementDirection) Valid() bool {
	switch e {
	case Credit:
		return true
	case Debit:
		return true
	default:
		return false
	}
}

// Defines values for ValidationErrorCode.
const (
	ValidationErrorCodeValidationError ValidationErrorCode = "validation_error"
)

// Valid indicates whether the value is a known member of the ValidationErrorCode enum.
func (e ValidationErrorCode) Valid() bool {
	switch e {
	case ValidationErrorCodeValidationError:
		return true
	default:
		return false
	}
}

// Defines values for ValidationErrorDetailCode.
const (
	InvalidFormat ValidationErrorDetailCode = "invalid_format"
	InvalidType   ValidationErrorDetailCode = "invalid_type"
	InvalidValue  ValidationErrorDetailCode = "invalid_value"
	MaxLength     ValidationErrorDetailCode = "max_length"
	MinLength     ValidationErrorDetailCode = "min_length"
	Required      ValidationErrorDetailCode = "required"
	UnknownField  ValidationErrorDetailCode = "unknown_field"
)

// Valid indicates whether the value is a known member of the ValidationErrorDetailCode enum.
func (e ValidationErrorDetailCode) Valid() bool {
	switch e {
	case InvalidFormat:
		return true
	case InvalidType:
		return true
	case InvalidValue:
		return true
	case MaxLength:
		return true
	case MinLength:
		return true
	case Required:
		return true
	case UnknownField:
		return true
	default:
		return false
	}
}

// Defines values for ValidationErrorDetailLocation.
const (
	Body    ValidationErrorDetailLocation = "body"
	Header  ValidationErrorDetailLocation = "header"
	Path    ValidationErrorDetailLocation = "path"
	Query   ValidationErrorDetailLocation = "query"
	Request ValidationErrorDetailLocation = "request"
)

// Valid indicates whether the value is a known member of the ValidationErrorDetailLocation enum.
func (e ValidationErrorDetailLocation) Valid() bool {
	switch e {
	case Body:
		return true
	case Header:
		return true
	case Path:
		return true
	case Query:
		return true
	case Request:
		return true
	default:
		return false
	}
}

// AccountBalances defines model for AccountBalances.
type AccountBalances struct {
	// CreditsPending Total pending credit amount in minor units.
	//
	// Example: 0
	CreditsPending int64 `json:"credits_pending"`

	// CreditsPosted Total posted credit amount in minor units.
	//
	// Example: 10000
	CreditsPosted int64 `json:"credits_posted"`

	// DebitsPending Total pending debit amount in minor units.
	//
	// Example: 200
	DebitsPending int64 `json:"debits_pending"`

	// DebitsPosted Total posted debit amount in minor units.
	//
	// Example: 0
	DebitsPosted int64 `json:"debits_posted"`
}

// AccountReference Stable opaque reference assigned to an account by the ledger.
//
// Example: acct_01K33YV8M82N9MXP4E7J6B1QWK
type AccountReference = string

// AccountStatus Whether the payable account itself is open or closed.
//
// Example: open
type AccountStatus string

// AvailableBalance Derived available amount in minor units (credits_posted - debits_posted - debits_pending).
//
// Example: 9800
type AvailableBalance = int64

// CreatePayableAccountRequest defines model for CreatePayableAccountRequest.
type CreatePayableAccountRequest struct {
	ExternalID string `json:"external_id"`

	// Ledger Opaque identifier assigned to the ledger.
	//
	// Example: ngn_ng
	Ledger LedgerSlug `json:"ledger"`
	Name   string     `json:"name"`
}

// CreatePayableAccountResponse defines model for CreatePayableAccountResponse.
type CreatePayableAccountResponse struct {
	// Available Derived available amount in minor units (credits_posted - debits_posted - debits_pending).
	//
	// Example: 9800
	Available AvailableBalance `json:"available"`
	Balances  AccountBalances  `json:"balances"`
	ClosedAt  *time.Time       `json:"closed_at"`
	CreatedAt time.Time        `json:"created_at"`

	// ExternalID Example: merchant_123
	ExternalID string `json:"external_id"`

	// HolderReference Stable opaque reference assigned to a holder by the ledger.
	//
	// Example: hld_01K33YVADP5Z8B0T3X2Q91C6RH
	HolderReference HolderReference `json:"holder_reference"`

	// Kind Example: payable
	Kind PayableAccountKind `json:"kind"`

	// LedgerSlug Opaque identifier assigned to the ledger.
	//
	// Example: ngn_ng
	LedgerSlug LedgerSlug `json:"ledger_slug"`

	// Name Example: Acme Ltd
	Name string `json:"name"`

	// Reference Stable opaque reference assigned to an account by the ledger.
	//
	// Example: acct_01K33YV8M82N9MXP4E7J6B1QWK
	Reference AccountReference `json:"reference"`

	// Status Whether the payable account itself is open or closed.
	//
	// Example: open
	Status AccountStatus `json:"status"`
}

// ErrorCode defines model for ErrorCode.
type ErrorCode string

// ErrorInfo defines model for ErrorInfo.
type ErrorInfo struct {
	Code ErrorCode `json:"code"`
}

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	Error   ErrorInfo `json:"error"`
	Message string    `json:"message"`
}

// GetAccountResponse Example: {"available":9800,"balances":{"credits_pending":0,"credits_posted":10000,"debits_pending":200,"debits_posted":0},"closed_at":null,"created_at":"2026-09-08T10:30:00Z","holder_reference":"hld_01K33YVADP5Z8B0T3X2Q91C6RH","kind":"payable","ledger_slug":"ngn_ng","name":"Acme Ltd","reference":"acct_01K33YV8M82N9MXP4E7J6B1QWK","status":"open"}
type GetAccountResponse struct {
	// Available Derived available amount in minor units (credits_posted - debits_posted - debits_pending).
	//
	// Example: 9800
	Available AvailableBalance `json:"available"`
	Balances  AccountBalances  `json:"balances"`
	ClosedAt  *time.Time       `json:"closed_at"`
	CreatedAt time.Time        `json:"created_at"`

	// HolderReference Stable opaque reference assigned to a holder by the ledger.
	//
	// Example: hld_01K33YVADP5Z8B0T3X2Q91C6RH
	HolderReference HolderReference `json:"holder_reference"`

	// Kind Example: payable
	Kind PayableAccountKind `json:"kind"`

	// LedgerSlug Opaque identifier assigned to the ledger.
	//
	// Example: ngn_ng
	LedgerSlug LedgerSlug `json:"ledger_slug"`

	// Name Example: Acme Ltd
	Name string `json:"name"`

	// Reference Stable opaque reference assigned to an account by the ledger.
	//
	// Example: acct_01K33YV8M82N9MXP4E7J6B1QWK
	Reference AccountReference `json:"reference"`

	// Status Whether the payable account itself is open or closed.
	//
	// Example: open
	Status AccountStatus `json:"status"`
}

// GetAccountStatementResponse defines model for GetAccountStatementResponse.
type GetAccountStatementResponse struct {
	Account StatementAccount `json:"account"`

	// ClosingBalance Posted balance at the end of the requested period in minor units.
	//
	// Example: 9600
	ClosingBalance int64               `json:"closing_balance"`
	Entries        []StatementMovement `json:"entries"`

	// OpeningBalance Posted balance before the requested period in minor units.
	//
	// Example: 0
	OpeningBalance int64           `json:"opening_balance"`
	Page           StatementPage   `json:"page"`
	Period         StatementPeriod `json:"period"`
}

// HealthResponse defines model for HealthResponse.
type HealthResponse struct {
	// Status Example: ok
	Status string `json:"status"`
}

// HolderReference Stable opaque reference assigned to a holder by the ledger.
//
// Example: hld_01K33YVADP5Z8B0T3X2Q91C6RH
type HolderReference = string

// IdempotencyKey Caller-generated identifier used to make a ledger operation idempotent.
//
// Example: payment_123
type IdempotencyKey = string

// JournalEntryKind Business classification of a journal entry.
type JournalEntryKind = string

// JournalRef Stable opaque reference assigned to a journal entry by the ledger.
//
// Example: jrn_01K33YW0MDHJ9E4N7Z2QPV6R8K
type JournalRef = string

// LedgerSlug Opaque identifier assigned to the ledger.
//
// Example: ngn_ng
type LedgerSlug = string

// PayableAccountKind Example: payable
type PayableAccountKind string

// PostJournalEntryLine defines model for PostJournalEntryLine.
type PostJournalEntryLine struct {
	// Amount Positive amount expressed in the ledger's minor units.
	//
	// Example: 10000
	Amount int64 `json:"amount"`

	// CreditAccountRef Stable opaque reference assigned to an account by the ledger.
	//
	// Example: acct_01K33YV8M82N9MXP4E7J6B1QWK
	CreditAccountRef AccountReference `json:"credit_account_ref"`

	// DebitAccountRef Stable opaque reference assigned to an account by the ledger.
	//
	// Example: acct_01K33YV8M82N9MXP4E7J6B1QWK
	DebitAccountRef AccountReference `json:"debit_account_ref"`

	// Purpose What this line's amount is for within the entry, such as a fee or tax. Client-defined.
	Purpose string `json:"purpose"`
}

// PostJournalEntryRequest defines model for PostJournalEntryRequest.
type PostJournalEntryRequest struct {
	Description string     `json:"description"`
	EffectiveAt *time.Time `json:"effective_at,omitempty"`

	// Kind Business classification of a journal entry.
	Kind JournalEntryKind `json:"kind"`

	// Ledger Opaque identifier assigned to the ledger.
	//
	// Example: ngn_ng
	Ledger LedgerSlug             `json:"ledger"`
	Lines  []PostJournalEntryLine `json:"lines"`
}

// PostJournalEntryResponse defines model for PostJournalEntryResponse.
type PostJournalEntryResponse struct {
	CreatedAt   time.Time `json:"created_at"`
	Description string    `json:"description"`
	EffectiveAt time.Time `json:"effective_at"`

	// JournalRef Stable opaque reference assigned to a journal entry by the ledger.
	//
	// Example: jrn_01K33YW0MDHJ9E4N7Z2QPV6R8K
	JournalRef JournalRef `json:"journal_ref"`

	// Kind Business classification of a journal entry.
	Kind JournalEntryKind `json:"kind"`

	// LedgerSlug Opaque identifier assigned to the ledger.
	//
	// Example: ngn_ng
	LedgerSlug LedgerSlug                    `json:"ledger_slug"`
	State      PostJournalEntryResponseState `json:"state"`
}

// PostJournalEntryResponseState defines model for PostJournalEntryResponse.State.
type PostJournalEntryResponseState string

// StatementAccount defines model for StatementAccount.
type StatementAccount struct {
	// HolderReference Stable opaque reference assigned to a holder by the ledger.
	//
	// Example: hld_01K33YVADP5Z8B0T3X2Q91C6RH
	HolderReference HolderReference `json:"holder_reference"`

	// Name Example: Acme Ltd
	Name string `json:"name"`

	// Reference Stable opaque reference assigned to an account by the ledger.
	//
	// Example: acct_01K33YV8M82N9MXP4E7J6B1QWK
	Reference AccountReference `json:"reference"`
}

// StatementDirection Example: credit
type StatementDirection string

// StatementMovement defines model for StatementMovement.
type StatementMovement struct {
	// Amount Positive amount expressed in the ledger's minor units.
	//
	// Example: 9800
	Amount int64 `json:"amount"`

	// BalanceAfter Posted balance after this movement in minor units.
	//
	// Example: 9800
	BalanceAfter int64 `json:"balance_after"`

	// Description Example: Payment received
	Description string `json:"description"`

	// Direction Example: credit
	Direction StatementDirection `json:"direction"`

	// JournalReference Stable opaque reference assigned to a journal entry by the ledger.
	//
	// Example: jrn_01K33YW0MDHJ9E4N7Z2QPV6R8K
	JournalReference JournalRef `json:"journal_reference"`

	// Kind Business classification of a journal entry.
	Kind JournalEntryKind `json:"kind"`

	// LineNumber Example: 1
	LineNumber int `json:"line_number"`

	// Purpose Example: Card payment
	Purpose string `json:"purpose"`

	// RecordedAt Example: 2026-09-10T09:15:00Z
	RecordedAt time.Time `json:"recorded_at"`
}

// StatementPage defines model for StatementPage.
type StatementPage struct {
	// Limit Example: 50
	Limit int `json:"limit"`

	// NextCursor Example: eyJ...
	NextCursor     *string `json:"next_cursor"`
	PreviousCursor *string `json:"previous_cursor"`
}

// StatementPeriod defines model for StatementPeriod.
type StatementPeriod struct {
	// From Example: 2026-09-01T00:00:00Z
	From time.Time `json:"from"`

	// To Example: 2026-10-01T00:00:00Z
	To time.Time `json:"to"`
}

// ValidationError defines model for ValidationError.
type ValidationError struct {
	Code    ValidationErrorCode     `json:"code"`
	Details []ValidationErrorDetail `json:"details"`
}

// ValidationErrorCode defines model for ValidationError.Code.
type ValidationErrorCode string

// ValidationErrorDetail defines model for ValidationErrorDetail.
type ValidationErrorDetail struct {
	Code ValidationErrorDetailCode `json:"code"`

	// Field Example: external_id
	Field    string                        `json:"field"`
	Location ValidationErrorDetailLocation `json:"location"`

	// Message Example: external_id is required
	Message string `json:"message"`
}

// ValidationErrorDetailCode defines model for ValidationErrorDetail.Code.
type ValidationErrorDetailCode string

// ValidationErrorDetailLocation defines model for ValidationErrorDetail.Location.
type ValidationErrorDetailLocation string

// ValidationErrorResponse defines model for ValidationErrorResponse.
type ValidationErrorResponse struct {
	Error ValidationError `json:"error"`

	// Message Example: Request validation failed.
	Message string `json:"message"`
}

// InvalidRequest defines model for InvalidRequest.
type InvalidRequest = ValidationErrorResponse

// GetAccountStatementParams defines parameters for GetAccountStatement.
type GetAccountStatementParams struct {
	// From Inclusive recorded-time boundary.
	From *time.Time `form:"from,omitempty" json:"from,omitempty"`

	// To Exclusive recorded-time boundary.
	To *time.Time `form:"to,omitempty" json:"to,omitempty"`

	// Limit Bounded number of movements to return.
	Limit *int `form:"limit,omitempty" json:"limit,omitempty"`

	// Cursor Opaque token returned by a preceding request.
	Cursor *string `form:"cursor,omitempty" json:"cursor,omitempty"`
}

// PostJournalEntryParams defines parameters for PostJournalEntry.
type PostJournalEntryParams struct {
	// IdempotencyKey Caller-generated key that uniquely identifies this posting within the ledger.
	IdempotencyKey IdempotencyKey `json:"Idempotency-Key"`
}

// CreatePayableAccountJSONRequestBody defines body for CreatePayableAccount for application/json ContentType.
type CreatePayableAccountJSONRequestBody = CreatePayableAccountRequest

// PostJournalEntryJSONRequestBody defines body for PostJournalEntry for application/json ContentType.
type PostJournalEntryJSONRequestBody = PostJournalEntryRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// CreatePayableAccount Create a payable account in a ledger
	// (POST /accounts)
	CreatePayableAccount(w http.ResponseWriter, r *http.Request)
	// GetAccount Get a payable account and its balance
	// (GET /accounts/{account_reference})
	GetAccount(w http.ResponseWriter, r *http.Request, accountReference AccountReference)
	// GetAccountStatement Get a payable account statement
	// (GET /accounts/{account_reference}/statement)
	GetAccountStatement(w http.ResponseWriter, r *http.Request, accountReference AccountReference, params GetAccountStatementParams)
	// PostJournalEntry Post a journal entry to a ledger
	// (POST /entries)
	PostJournalEntry(w http.ResponseWriter, r *http.Request, params PostJournalEntryParams)
	// GetHealth Check whether the service is running
	// (GET /health)
	GetHealth(w http.ResponseWriter, r *http.Request)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// CreatePayableAccount operation middleware
func (siw *ServerInterfaceWrapper) CreatePayableAccount(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreatePayableAccount(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetAccount operation middleware
func (siw *ServerInterfaceWrapper) GetAccount(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "account_reference" -------------
	var accountReference AccountReference

	err = runtime.BindStyledParameterWithOptions("simple", "account_reference", r.PathValue("account_reference"), &accountReference, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "account_reference", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetAccount(w, r, accountReference)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetAccountStatement operation middleware
func (siw *ServerInterfaceWrapper) GetAccountStatement(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "account_reference" -------------
	var accountReference AccountReference

	err = runtime.BindStyledParameterWithOptions("simple", "account_reference", r.PathValue("account_reference"), &accountReference, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "account_reference", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params GetAccountStatementParams

	// ------------- Optional query parameter "from" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "from", r.URL.Query(), &params.From, runtime.BindQueryParameterOptions{Type: "string", Format: "date-time"})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "from"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "from", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "to" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "to", r.URL.Query(), &params.To, runtime.BindQueryParameterOptions{Type: "string", Format: "date-time"})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "to"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "to", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", r.URL.Query(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "limit"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "cursor" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "cursor", r.URL.Query(), &params.Cursor, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "cursor"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "cursor", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetAccountStatement(w, r, accountReference, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostJournalEntry operation middleware
func (siw *ServerInterfaceWrapper) PostJournalEntry(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params PostJournalEntryParams

	headers := r.Header

	// ------------- Required header parameter "Idempotency-Key" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("Idempotency-Key")]; found {
		var IdempotencyKey IdempotencyKey
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "Idempotency-Key", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "Idempotency-Key", valueList[0], &IdempotencyKey, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true, Type: "string", Format: ""})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "Idempotency-Key", Err: err})
			return
		}

		params.IdempotencyKey = IdempotencyKey

	} else {
		err := fmt.Errorf("Header parameter Idempotency-Key is required, but not found")
		siw.ErrorHandlerFunc(w, r, &RequiredHeaderError{ParamName: "Idempotency-Key", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostJournalEntry(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetHealth operation middleware
func (siw *ServerInterfaceWrapper) GetHealth(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetHealth(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

// ServeMux is an abstraction of [http.ServeMux].
type ServeMux interface {
	HandleFunc(pattern string, handler func(http.ResponseWriter, *http.Request))
	http.Handler
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/health", wrapper.GetHealth)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/accounts", wrapper.CreatePayableAccount)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/accounts/{account_reference}", wrapper.GetAccount)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/accounts/{account_reference}/statement", wrapper.GetAccountStatement)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/entries", wrapper.PostJournalEntry)

	return m
}

type InvalidRequestJSONResponse ValidationErrorResponse

type CreatePayableAccountRequestObject struct {
	Body *CreatePayableAccountJSONRequestBody
}

type CreatePayableAccountResponseObject interface {
	VisitCreatePayableAccountResponse(w http.ResponseWriter) error
}

type CreatePayableAccount200JSONResponse CreatePayableAccountResponse

func (response CreatePayableAccount200JSONResponse) VisitCreatePayableAccountResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type CreatePayableAccount201JSONResponse CreatePayableAccountResponse

func (response CreatePayableAccount201JSONResponse) VisitCreatePayableAccountResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)
	_, err := buf.WriteTo(w)
	return err
}

type CreatePayableAccount400JSONResponse struct{ InvalidRequestJSONResponse }

func (response CreatePayableAccount400JSONResponse) VisitCreatePayableAccountResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type CreatePayableAccount409JSONResponse ErrorResponse

func (response CreatePayableAccount409JSONResponse) VisitCreatePayableAccountResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(409)
	_, err := buf.WriteTo(w)
	return err
}

type CreatePayableAccount500JSONResponse ErrorResponse

func (response CreatePayableAccount500JSONResponse) VisitCreatePayableAccountResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type GetAccountRequestObject struct {
	AccountReference AccountReference `json:"account_reference"`
}

type GetAccountResponseObject interface {
	VisitGetAccountResponse(w http.ResponseWriter) error
}

type GetAccount200JSONResponse GetAccountResponse

func (response GetAccount200JSONResponse) VisitGetAccountResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetAccount400JSONResponse struct{ InvalidRequestJSONResponse }

func (response GetAccount400JSONResponse) VisitGetAccountResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type GetAccount404JSONResponse ErrorResponse

func (response GetAccount404JSONResponse) VisitGetAccountResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type GetAccount500JSONResponse ErrorResponse

func (response GetAccount500JSONResponse) VisitGetAccountResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type GetAccountStatementRequestObject struct {
	AccountReference AccountReference `json:"account_reference"`
	Params           GetAccountStatementParams
}

type GetAccountStatementResponseObject interface {
	VisitGetAccountStatementResponse(w http.ResponseWriter) error
}

type GetAccountStatement200JSONResponse GetAccountStatementResponse

func (response GetAccountStatement200JSONResponse) VisitGetAccountStatementResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetAccountStatement400JSONResponse struct{ InvalidRequestJSONResponse }

func (response GetAccountStatement400JSONResponse) VisitGetAccountStatementResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type GetAccountStatement404JSONResponse ErrorResponse

func (response GetAccountStatement404JSONResponse) VisitGetAccountStatementResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type GetAccountStatement500JSONResponse ErrorResponse

func (response GetAccountStatement500JSONResponse) VisitGetAccountStatementResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type PostJournalEntryRequestObject struct {
	Params PostJournalEntryParams
	Body   *PostJournalEntryJSONRequestBody
}

type PostJournalEntryResponseObject interface {
	VisitPostJournalEntryResponse(w http.ResponseWriter) error
}

type PostJournalEntry200JSONResponse PostJournalEntryResponse

func (response PostJournalEntry200JSONResponse) VisitPostJournalEntryResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type PostJournalEntry201JSONResponse PostJournalEntryResponse

func (response PostJournalEntry201JSONResponse) VisitPostJournalEntryResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)
	_, err := buf.WriteTo(w)
	return err
}

type PostJournalEntry400JSONResponse struct{ InvalidRequestJSONResponse }

func (response PostJournalEntry400JSONResponse) VisitPostJournalEntryResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type PostJournalEntry404JSONResponse ErrorResponse

func (response PostJournalEntry404JSONResponse) VisitPostJournalEntryResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type PostJournalEntry409JSONResponse ErrorResponse

func (response PostJournalEntry409JSONResponse) VisitPostJournalEntryResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(409)
	_, err := buf.WriteTo(w)
	return err
}

type PostJournalEntry500JSONResponse ErrorResponse

func (response PostJournalEntry500JSONResponse) VisitPostJournalEntryResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type GetHealthRequestObject struct {
}

type GetHealthResponseObject interface {
	VisitGetHealthResponse(w http.ResponseWriter) error
}

type GetHealth200JSONResponse HealthResponse

func (response GetHealth200JSONResponse) VisitGetHealthResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// CreatePayableAccount Create a payable account in a ledger
	// (POST /accounts)
	CreatePayableAccount(ctx context.Context, request CreatePayableAccountRequestObject) (CreatePayableAccountResponseObject, error)
	// GetAccount Get a payable account and its balance
	// (GET /accounts/{account_reference})
	GetAccount(ctx context.Context, request GetAccountRequestObject) (GetAccountResponseObject, error)
	// GetAccountStatement Get a payable account statement
	// (GET /accounts/{account_reference}/statement)
	GetAccountStatement(ctx context.Context, request GetAccountStatementRequestObject) (GetAccountStatementResponseObject, error)
	// PostJournalEntry Post a journal entry to a ledger
	// (POST /entries)
	PostJournalEntry(ctx context.Context, request PostJournalEntryRequestObject) (PostJournalEntryResponseObject, error)
	// GetHealth Check whether the service is running
	// (GET /health)
	GetHealth(ctx context.Context, request GetHealthRequestObject) (GetHealthResponseObject, error)
}

type StrictHandlerFunc func(ctx context.Context, w http.ResponseWriter, r *http.Request, request any) (any, error)
type StrictMiddlewareFunc func(f StrictHandlerFunc, operationID string) StrictHandlerFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	if options.RequestErrorHandlerFunc == nil {
		options.RequestErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	if options.ResponseErrorHandlerFunc == nil {
		options.ResponseErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		}
	}
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// CreatePayableAccount operation middleware
func (sh *strictHandler) CreatePayableAccount(w http.ResponseWriter, r *http.Request) {
	var request CreatePayableAccountRequestObject

	var body CreatePayableAccountJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.CreatePayableAccount(ctx, request.(CreatePayableAccountRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreatePayableAccount")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(CreatePayableAccountResponseObject); ok {
		if err := validResponse.VisitCreatePayableAccountResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetAccount operation middleware
func (sh *strictHandler) GetAccount(w http.ResponseWriter, r *http.Request, accountReference AccountReference) {
	var request GetAccountRequestObject

	request.AccountReference = accountReference

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetAccount(ctx, request.(GetAccountRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetAccount")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetAccountResponseObject); ok {
		if err := validResponse.VisitGetAccountResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetAccountStatement operation middleware
func (sh *strictHandler) GetAccountStatement(w http.ResponseWriter, r *http.Request, accountReference AccountReference, params GetAccountStatementParams) {
	var request GetAccountStatementRequestObject

	request.AccountReference = accountReference
	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetAccountStatement(ctx, request.(GetAccountStatementRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetAccountStatement")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetAccountStatementResponseObject); ok {
		if err := validResponse.VisitGetAccountStatementResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// PostJournalEntry operation middleware
func (sh *strictHandler) PostJournalEntry(w http.ResponseWriter, r *http.Request, params PostJournalEntryParams) {
	var request PostJournalEntryRequestObject

	request.Params = params

	var body PostJournalEntryJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.PostJournalEntry(ctx, request.(PostJournalEntryRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PostJournalEntry")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(PostJournalEntryResponseObject); ok {
		if err := validResponse.VisitPostJournalEntryResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetHealth operation middleware
func (sh *strictHandler) GetHealth(w http.ResponseWriter, r *http.Request) {
	var request GetHealthRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetHealth(ctx, request.(GetHealthRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetHealth")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetHealthResponseObject); ok {
		if err := validResponse.VisitGetHealthResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"7Dzpcts4mq+CYk/VdPfSMiXf2h9bPnI4Tnodx5Vkc6wCkR8txBSgAKBjTax338JBEjwkUYqdbE3nT8ci",
	"CeC7b/Q3L2TjCaNApfD63zwOYsKoAP3jlN7ghEQX8CUFIdWTkFEJVP+JJ5OEhFgSRjc/C0bVMxGOYIzV",
	"X//gEHt977fNYvtN81Zsvlab6oWPOGf8wh7pzWYz34tAhJxM1Fuv712OAHFzPIoYCESZRAJLIuIpkiNA",
	"h+enSAHFcSg7ntrAnqKAOAxDllJ5hBNMQ4MSjiKi9sbJOWcT4JKo5zFOBPjexHn0zQs5RESKwQRoROiV",
	"elQBjkmcIPsamc8RHqsjEaFoTCjjKKVEio7ne3CLx5MEvH7gezHjYyy9vkeo3N32fG9MKBmnY/1STidg",
	"XsEVcG/mF5AwISGaC4h+2x6ObhAEq8MSwXAFouivW8DS+w5I2hClLRyrQjHzPSWehCsI3leJ49dkqAp1",
	"jbcf8zPY8DOEUiFqxfgCYuBAQ6jj+kriYQKITfCXVCmM/RBhIcgVhQhJhjBF2GyEhkZ3EoiugJfw93AY",
	"ykHQPdva+p/X+y/2e38dvHh7vv1o79nuUfflmzNFDnz7HOiVHHn93W1NnexnN4ddSG6wvd24yZV9YwxC",
	"4CujXM4u3jgVUis23IYAEdrdRuEIK40GLrzSEcW3Q0Awnsip5oGl0CuJZSrq5HkzAjkCrpGe4KmmVUYL",
	"IgUkMSICsQlQxDgKEyYg0mShiu3vPfVGsUq/UCwq6GVflfFWEN1gkqiDrPGpA3UCnNxAhHD2ZbN4ot/L",
	"EoI2UEmEnN9Gxv4oMfRgfw3NOuaAJZwbSuXSlzuBspmEWwmc4mRAogpjezs7VfmYYKm+9vpe588PH151",
	"/vSaZOaKbVA8Vg8f2c1PT9YVpt7OzirS5ILovh0mmF4XwOpXQ0AYZSyf+Z7Rp2Xe77n+6lWSajkxeN4P",
	"2f4/U6diKC2p/JL0WGo0mcBmibRxw2puPde3ZYyqqfDM94ZOKLFwbSXymGXWY4C1CuUKGWEJG5KMQWGf",
	"JhYwyVNoMCqhpsLCPWprKupZWK4x8HCEqRx0e1vecjveqJMz3xuxJAI+4K5zWkSZp/r7wpfNfO+a0GjZ",
	"sjLrz9SKXOMGQinTWmpXkOMwHAN6LqMlpNBy3BLVmt9W0WnuolqstP6sqjw1krswlYnSqGCW4jkwrmz6",
	"jn444l6SvSYF1ZH8MYsMVa3ftJBYv5nLSshonJBQH2YQHVAmBzFLNVTZs3wZoSKNYxISoHIQpzRS8JAI",
	"xhMmgYZTd0PlxTS6AvgN8AEouByICzZqiE9pzFZNCyySi/hXUKPKO716LgHXNGkGyTYwaXxnvmf9g3YP",
	"i6S9An22zPeqdC0QeQJyVQOda2HJOpvQxbW4tYwsqOdGNquppik996H9NChbZWV+yzbW6wW93Y3gYCPY",
	"v+wG/a2gHwTvvCab542SKAubD0/Od97tHwWXW297Lw+6x7sXTzOV63s2/Kyoad+jV3SgLa01so45co9Z",
	"Hp5nBsZEprO/uff75Z1+uHdyXVGDpyp7J+uIrFu6R39UWCEFJoxh/XjRbLOMKPkx9thM6Am9Ggzn5YDn",
	"JoWz7xGWOkUFGiEW6z9t7QsiNAFOWLSodnGw25jq1dM7oJJb5IiEsWiN2gt2o/9Vm9htMed4qn4rc7MK",
	"rkOIGYeVkWyH4cT6tlZYnauP1SJ9ePtl5vOq+Gfiku9XJ01dMAqeWNibRPop4ESO1pTiQrOd2sW1t8zh",
	"22WN4FRM5XpFKWRMxKKS1FLXukJFauZ7p0XgeAbTOtjHOEmAb1wBBa4sDCIRUEliAhylwoA9xtcquzXQ",
	"IkVnnXajPCiVZRQmeKpEJku1/s1zfd97xlIVhD+ikk/PrP8sU/koFYSCEChMlDzEtpOg7B5Gn81ypJRi",
	"2lnG4Qcj2Gp1yHug14UyO+upUYlki7TpM6dWm94EL06ePjt4tP3X3rvey/PXuxf7ZytrkxO41CD/bwOy",
	"oz8uzPMAzCNhF5CtEiBbLq3/9z3e+FewcfDxP37/r/4g//HHn/+4NznYWiIHIaMSE6r8dwJYSFRZUBGM",
	"7POEfQUeYqHooD4QCNMI0XQ8VH8LmGBjgIZTpLxFAiilEXARMq49xSKJaohIncQ8y0I+VoyUDbNqXFa+",
	"29Xp54RCvRJs6teNnp9IcpMXuOF2wkEoU0qoIwb/FKu3qvCtKWMf9HpbW3u9YGt3f2d7b29Xf54Xubu1",
	"GGGxJJhVNTlQoNq3SKSTCeOKOxZr57icI1c6RuVIjjBF/wLOGphGkdtMMtnsICuBcGMQVg3jdZ77vZtM",
	"Uj5hApq6KTpOJQIlhMI/Rd63EChmHH0lcmT5qo2Rj0QajhAWCKMYADGOJL7toOOEAJUbEcSEmnaLo4Nd",
	"y78fYea7QfBTauB1LjXy3/dyCctY0hSOVVV0br+mxMwSZXZ+INF3fhTRfQ/iGEJlf1aqHLRJ+2thzppN",
	"IKVH7dOxRmM80+pzatZn2pP9rGRri1lmFxVkztzV2ORrmGqNyQIOA7t73ByfyCiUFjXaQptOzm0X2XqB",
	"K8MZ+dopxVrJ0zqVp6qaLQ6j1pNRS842Ft6JML9buNeoaKk8stQaqI07zElAXRTnFI/M3lWhKFF0abmo",
	"Vr1ZTUDuocz4k2p+qxXv5vZnc/qdEK7IboQ+Y7b2dLl3K0ed9lkDVvWy04qFuwcLR5cNVXSbalK21jPA",
	"sTT+YXEpMDaBIxFobNFfWPvbb1n7q5ilgg/npkSBOIRAbqCF1EUuq1uVzArhKBuvdsJ7TyaMUBiYHKtE",
	"gO4y/jnxcEG1Y8wjZKs7bfQ0ZDzKHUmxTdZn6gaXwUG/u2P7TG28wHx7WZTcHZQLF5rzwgkwyzJaNakZ",
	"BcqILDQH57YQu4LaJmRMyuTZCZxMr7sks1OmFG7lIEy5YGUWezB91ul02vSaJhxuCEuFs82SNdWIRWNR",
	"36gM3WLa5fXoFagXczZulq2gexkE/SBYQbZ8T7KGzbrBOptVCKQB1Qc0EaEyIrxmiz7zP0Wwu2AeIAKJ",
	"SdI+DK+AeKKX6zh8buDdOAxQnNyCEPaU7yNHDoLvETPhPdDnFj8tP4sHNzhJwRi4QWIsnNbJ4kdKryn7",
	"SgcxgSRqJLB5U1bI0nDKEuuZMFMjrqKislydHyowvqTAVYYzAhxpEzZk0bQRHGcEohEgRARyKLXKmEQO",
	"aYa0n7E6O7QFqx9yFqSqXvPIYYsIqFAgFGOS2HLNvQ6OqBXETuOUI6Onl5fnes4/ZtyJz5AAfkNCUKBI",
	"IjW8JulQH3u+dwNcmB2CTrcTZE1KPCFe39vqBJ0tKzaabpu25qJ/qOxE/Zt3dk4j5ewbhhA9P5PBIyVo",
	"93VFYtEEbiU7Vt5IP3AubvSC4IFBmX9l45Dain+Ik/zuxlcsUOYKkylSxyQgIfpPUye8JUISelUMZSvV",
	"kynXhcGZ7/WC7k/D57JhaFyhYzNKDd+2oXfTsTlfNiu3afSygxZoWXV0Es3jbN5NIZ2Ox5hPLaC2m2oY",
	"IBWhzZdCl2URpgWtzadKT7Rtd02HcRi1cT3XStj2L1Iqq3yFMg1LD+s4Y9LHZrqvhoFVbiJQPv83F8Dy",
	"fGEJvOeVbTqGte1EZKVrSRWsSwlkmHKukipdotCSstNKM52BuCrOzQOOJdwVdOYtClmaRLaKZ1TOnbjQ",
	"EN0jSdoeqk7NmW70EeH6zQyat9j1ktxCb35z6uMmy5kp+K+gIdu/AMkJ3IDQBcjqGZhGKv9nAgQaMjlC",
	"RAoUzbuZob5WH+g2XDJVgm3FVe8GXHTQpUrZlbfKr6uZ/VHGOBRiMUKMIw43QNMcFp3Qlx1OMcSkPRXH",
	"Y9DV8v77bx6humWngx47M1ijilf1E2253VAn+viALqZhZHQFQ6znhjVvMp9hNFFxKhsY+z4rvf19Klsf",
	"ci6pq0Vdy4p+fd9q6cxXVcjnyCix5uCXgaoaqCcgG6xTZguyEa6lFmpTZIl9C1ulwMmaJVn9TyBsatr0",
	"qtGW2cYrRll1RifidqbOz4qb6o0Oo6foK3BAmrvFREa22e+fnBqPj4QiDQ3h0x+dD/QD/e2339AjIwIF",
	"eOrFHbqwyxCW6A7ZCpwztnKHzgiN0B3Ki4HoDh0a+3qH7MgwulNbbWxsoDn/7ef/qA+L8hnS5TN0hz6Z",
	"OZcXveBZ9+VJ7+3R/tnek+2/Do5fP9693Dr8hO6ysh26Q8fmyuwdOvD3g6D49z72PtE3T9U+ZuNds/EC",
	"W58XgH6+0ferEnpKwyQV5AYqQjZUdgubYS0NZJaHWyhttacApF3FqHr8o9v1jpfsHg4/UodANqCDWOxo",
	"pmTW+cyDIKsHFkBEEOM0kauWN+tw2TErya6BFi5wOFVGi0MI+iJ2btuawcurkwV8VXqsFwC4VzuK1trc",
	"CxQvesHTvbdn24cHL3uX7/ZfP9k9eny+1b1oezFCrd/fC7Yfdx+fvOgeP37z6t3J62fnrxunsc3AdD4N",
	"/b5oGZWunmQdG/Ow0rWpd02ctkjR3GpodniLrUjpyoi1BqXeRddpSVT7EKVGQ3N3QclRhm6vCdvdlbHN",
	"2nwPgGzPRfacsxCE4iWKAVqi+7FhRD0oJsVt10HpYql94Jm5y4H7sKE9QNMkKY2Qmzr8vOK7ZPNq6e2T",
	"1EU3HFpGz3lEouNokYaKrHGaJFNlR3QoEv2KnH9FzvcbORdxsI6ZndsozWXX6hBPPSxaMsB/DVMkR1ii",
	"lJIvKSTTYiRZmBa7OliZE2d2sRhN1v4y7ydYN+TcItg4g+naQVflNoJ1s/dfUJ43HviDi8lzB7LuuZBs",
	"xuAfsoy8CiaXTjZnINNo6ImPv619PSySwmiOWUUVXVyrZG63bqo3N4LQqvJcuaPeSLVS7bl0YX1+/d75",
	"SJutirjr+0cx4ygisQbczFmagGkusI1X5Usgn1aOrVbycxjKlt69mP9Y38svk9f5Pw7ZvJ6DyidM2v9V",
	"+5Ih2JHgxQRv+H8AlDFw3iP9/t+q2ZA5qApjcnuXtUR/9RnmBiPKYNcuSum7U26PYaQvWToVulqVxlzD",
	"9B7QSVYuei4gAglBSZ0BelrrrIwgvEZfnf/5lbOGp5Taawmz/wsAAP//",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
