//go:build go1.22

// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/flate"
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/oapi-codegen/runtime"
)

// Defines values for ErrorCode.
const (
	HolderConflict      ErrorCode = "holder_conflict"
	InternalServerError ErrorCode = "internal_server_error"
	LedgerClosed        ErrorCode = "ledger_closed"
	LedgerNotFound      ErrorCode = "ledger_not_found"
)

// Valid indicates whether the value is a known member of the ErrorCode enum.
func (e ErrorCode) Valid() bool {
	switch e {
	case HolderConflict:
		return true
	case InternalServerError:
		return true
	case LedgerClosed:
		return true
	case LedgerNotFound:
		return true
	default:
		return false
	}
}

// Defines values for ValidationErrorCode.
const (
	ValidationErrorCodeValidationError ValidationErrorCode = "validation_error"
)

// Valid indicates whether the value is a known member of the ValidationErrorCode enum.
func (e ValidationErrorCode) Valid() bool {
	switch e {
	case ValidationErrorCodeValidationError:
		return true
	default:
		return false
	}
}

// Defines values for ValidationErrorDetailCode.
const (
	InvalidFormat ValidationErrorDetailCode = "invalid_format"
	InvalidType   ValidationErrorDetailCode = "invalid_type"
	MaxLength     ValidationErrorDetailCode = "max_length"
	MinLength     ValidationErrorDetailCode = "min_length"
	Required      ValidationErrorDetailCode = "required"
	UnknownField  ValidationErrorDetailCode = "unknown_field"
)

// Valid indicates whether the value is a known member of the ValidationErrorDetailCode enum.
func (e ValidationErrorDetailCode) Valid() bool {
	switch e {
	case InvalidFormat:
		return true
	case InvalidType:
		return true
	case MaxLength:
		return true
	case MinLength:
		return true
	case Required:
		return true
	case UnknownField:
		return true
	default:
		return false
	}
}

// Defines values for ValidationErrorDetailLocation.
const (
	Body    ValidationErrorDetailLocation = "body"
	Path    ValidationErrorDetailLocation = "path"
	Query   ValidationErrorDetailLocation = "query"
	Request ValidationErrorDetailLocation = "request"
)

// Valid indicates whether the value is a known member of the ValidationErrorDetailLocation enum.
func (e ValidationErrorDetailLocation) Valid() bool {
	switch e {
	case Body:
		return true
	case Path:
		return true
	case Query:
		return true
	case Request:
		return true
	default:
		return false
	}
}

// AccountRef Stable opaque reference assigned to an account by the ledger.
//
// Example: acct_01K33YV8M82N9MXP4E7J6B1QWK
type AccountRef = string

// CreatePayableAccountRequest defines model for CreatePayableAccountRequest.
type CreatePayableAccountRequest struct {
	ExternalID string `json:"external_id"`
	Name       string `json:"name"`
}

// CreatePayableAccountResponse defines model for CreatePayableAccountResponse.
type CreatePayableAccountResponse struct {
	// AccountRef Stable opaque reference assigned to an account by the ledger.
	//
	// Example: acct_01K33YV8M82N9MXP4E7J6B1QWK
	AccountRef AccountRef `json:"account_ref"`
	CreatedAt  time.Time  `json:"created_at"`

	// ExternalID Example: merchant_123
	ExternalID string `json:"external_id"`

	// HolderRef Stable opaque reference assigned to a holder by the ledger.
	//
	// Example: hld_01K33YVADP5Z8B0T3X2Q91C6RH
	HolderRef HolderRef `json:"holder_ref"`

	// LedgerSlug Opaque identifier assigned to the ledger.
	//
	// Example: ngn_ng
	LedgerSlug LedgerSlug `json:"ledger_slug"`

	// Name Example: Acme Ltd
	Name string `json:"name"`
}

// ErrorCode defines model for ErrorCode.
type ErrorCode string

// ErrorInfo defines model for ErrorInfo.
type ErrorInfo struct {
	Code ErrorCode `json:"code"`
}

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	Error   ErrorInfo `json:"error"`
	Message string    `json:"message"`
}

// HealthResponse defines model for HealthResponse.
type HealthResponse struct {
	// Status Example: ok
	Status string `json:"status"`
}

// HolderRef Stable opaque reference assigned to a holder by the ledger.
//
// Example: hld_01K33YVADP5Z8B0T3X2Q91C6RH
type HolderRef = string

// LedgerSlug Opaque identifier assigned to the ledger.
//
// Example: ngn_ng
type LedgerSlug = string

// ValidationError defines model for ValidationError.
type ValidationError struct {
	Code    ValidationErrorCode     `json:"code"`
	Details []ValidationErrorDetail `json:"details"`
}

// ValidationErrorCode defines model for ValidationError.Code.
type ValidationErrorCode string

// ValidationErrorDetail defines model for ValidationErrorDetail.
type ValidationErrorDetail struct {
	Code ValidationErrorDetailCode `json:"code"`

	// Field Example: external_id
	Field    string                        `json:"field"`
	Location ValidationErrorDetailLocation `json:"location"`

	// Message Example: external_id is required
	Message string `json:"message"`
}

// ValidationErrorDetailCode defines model for ValidationErrorDetail.Code.
type ValidationErrorDetailCode string

// ValidationErrorDetailLocation defines model for ValidationErrorDetail.Location.
type ValidationErrorDetailLocation string

// ValidationErrorResponse defines model for ValidationErrorResponse.
type ValidationErrorResponse struct {
	Error ValidationError `json:"error"`

	// Message Example: Request validation failed.
	Message string `json:"message"`
}

// InvalidRequest defines model for InvalidRequest.
type InvalidRequest = ValidationErrorResponse

// CreatePayableAccountJSONRequestBody defines body for CreatePayableAccount for application/json ContentType.
type CreatePayableAccountJSONRequestBody = CreatePayableAccountRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// GetHealth Check whether the service is running
	// (GET /health)
	GetHealth(w http.ResponseWriter, r *http.Request)
	// CreatePayableAccount Create a payable account in a ledger
	// (POST /ledgers/{slug}/accounts)
	CreatePayableAccount(w http.ResponseWriter, r *http.Request, slug LedgerSlug)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// GetHealth operation middleware
func (siw *ServerInterfaceWrapper) GetHealth(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetHealth(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreatePayableAccount operation middleware
func (siw *ServerInterfaceWrapper) CreatePayableAccount(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "slug" -------------
	var slug LedgerSlug

	err = runtime.BindStyledParameterWithOptions("simple", "slug", r.PathValue("slug"), &slug, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "slug", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreatePayableAccount(w, r, slug)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

// ServeMux is an abstraction of [http.ServeMux].
type ServeMux interface {
	HandleFunc(pattern string, handler func(http.ResponseWriter, *http.Request))
	http.Handler
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/health", wrapper.GetHealth)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/ledgers/{slug}/accounts", wrapper.CreatePayableAccount)

	return m
}

type InvalidRequestJSONResponse ValidationErrorResponse

type GetHealthRequestObject struct {
}

type GetHealthResponseObject interface {
	VisitGetHealthResponse(w http.ResponseWriter) error
}

type GetHealth200JSONResponse HealthResponse

func (response GetHealth200JSONResponse) VisitGetHealthResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type CreatePayableAccountRequestObject struct {
	Slug LedgerSlug `json:"slug"`
	Body *CreatePayableAccountJSONRequestBody
}

type CreatePayableAccountResponseObject interface {
	VisitCreatePayableAccountResponse(w http.ResponseWriter) error
}

type CreatePayableAccount200JSONResponse CreatePayableAccountResponse

func (response CreatePayableAccount200JSONResponse) VisitCreatePayableAccountResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type CreatePayableAccount201JSONResponse CreatePayableAccountResponse

func (response CreatePayableAccount201JSONResponse) VisitCreatePayableAccountResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)
	_, err := buf.WriteTo(w)
	return err
}

type CreatePayableAccount400JSONResponse struct{ InvalidRequestJSONResponse }

func (response CreatePayableAccount400JSONResponse) VisitCreatePayableAccountResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type CreatePayableAccount404JSONResponse ErrorResponse

func (response CreatePayableAccount404JSONResponse) VisitCreatePayableAccountResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type CreatePayableAccount409JSONResponse ErrorResponse

func (response CreatePayableAccount409JSONResponse) VisitCreatePayableAccountResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(409)
	_, err := buf.WriteTo(w)
	return err
}

type CreatePayableAccount500JSONResponse ErrorResponse

func (response CreatePayableAccount500JSONResponse) VisitCreatePayableAccountResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// GetHealth Check whether the service is running
	// (GET /health)
	GetHealth(ctx context.Context, request GetHealthRequestObject) (GetHealthResponseObject, error)
	// CreatePayableAccount Create a payable account in a ledger
	// (POST /ledgers/{slug}/accounts)
	CreatePayableAccount(ctx context.Context, request CreatePayableAccountRequestObject) (CreatePayableAccountResponseObject, error)
}

type StrictHandlerFunc func(ctx context.Context, w http.ResponseWriter, r *http.Request, request any) (any, error)
type StrictMiddlewareFunc func(f StrictHandlerFunc, operationID string) StrictHandlerFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	if options.RequestErrorHandlerFunc == nil {
		options.RequestErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	if options.ResponseErrorHandlerFunc == nil {
		options.ResponseErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		}
	}
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// GetHealth operation middleware
func (sh *strictHandler) GetHealth(w http.ResponseWriter, r *http.Request) {
	var request GetHealthRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetHealth(ctx, request.(GetHealthRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetHealth")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetHealthResponseObject); ok {
		if err := validResponse.VisitGetHealthResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// CreatePayableAccount operation middleware
func (sh *strictHandler) CreatePayableAccount(w http.ResponseWriter, r *http.Request, slug LedgerSlug) {
	var request CreatePayableAccountRequestObject

	request.Slug = slug

	var body CreatePayableAccountJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.CreatePayableAccount(ctx, request.(CreatePayableAccountRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreatePayableAccount")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(CreatePayableAccountResponseObject); ok {
		if err := validResponse.VisitCreatePayableAccountResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"zFhtc9s2Ev4rGFxm7i5HS7Jl+2L1Q8dxMrWbpHUcT5o2STUQuZIQgwADgLZVj/57ZwHw1bQsuc6030ji",
	"ZZ/dffaNNzRWaaYkSGvo6IZqMJmSBtzLibxkgidn8DUHY/FLrKQF6R5ZlgkeM8uV7H8xSuI3E88hZfj0",
	"RMOUjui/+tX1fb9q+u/xUnfwpdZKnwWRdLlcRjQBE2ue4Sod0fM5EO3Fk0SBIVJZYpjlZrogdg7k8PSE",
	"ICjNYtujeEGQgiAO41jl0p4hlJvWze8smwggKmNfc5QxBQ0yBsKM4TMJCbGKMEmYv4JMvDgByQx0j0YU",
	"rlmaCaAjyuLYjgfbr4bDX98/e/Ns56eDNx9Od1/+/8f959tvf3lFI5qy69cgZ3ZOR/u7EU25LF63I2oX",
	"Gd5irOZyRpcRPdLALJyyBQIsVShdkGmVgbbcuwiuLWjJxJgn+FqTtLO31xaVMYu76Yj2nn769K73lLbF",
	"R/R6a6a2JEvx48tw+ckLt3BZ+m0rBWPYzEOoyaRpbqzzEVzHAAnZ2dsj8Zyhd0Ab2gBUbZ4AgTSzC1qH",
	"WF+dCCYvKrBuaQKEkcJqy4h6zI9jgn+ypsuIYkRwDQkdfWwQIBjhc3lcTb5AbO8mVQg8jOYk4agvE6c1",
	"fk2ZMBC1KBdCYqx9WK2K9FoALiMaOwzJmDkeT5VO8YkmzMKW5SnQjmBo8buKuhR0PGfSjrd3hnR1TN1J",
	"6mVE50okoNfR5djtDKr4PDA2Ip/dd+612/oOd9ZYWilyGKdAXtvkHiXafq8BjxouaYKLugjScEUXW1xe",
	"PlKJhyrzFCWGa6Wy46nKZVJJioUygO8BVKzkVPDY0ohyGaQb0Jegx4A312RWnnYyT+RUbUjHOMBc5YNK",
	"n7YZ3ek7TfDACPFKroPJ6buMaMgyLslsQILiWETbdq0UOQYm7PyBmhjLbG6ahFUX9D5c4VgnnDKMHlaS",
	"iefYqoI8F0lRjw9fnO799uz54Hz4YeftwfbR/tnxxvW4FsC3IP/ssfIEpOVTDroB9i6AcibHLi/VgQwb",
	"QIb1AvH7R7b1x2Dr4PP//vP9aFy+/Pfpk8eqXvvDe4oX9liMS8IsEcCMJa0DrWpWbBfqCnTMDNoBNxjC",
	"ZEJknk7w2UDGNOYh9KbhciaA5DIBbWKlwThatZrFByaHIodVplmRiRKwjAt3nltIzYb97At33EU1lyf+",
	"gopXTGu26E5DleSuwOmW8tfMUULARO1sM3Zyq9dQpZ0uY+Ep4XhbveTyQqorOZ5yEEmnQf1KI4k0q9I9",
	"ESiUnzPa0LEjdtRDGF9z0NhXTVSy6ERRy7GdOAg3pGaQTfJwCbDQNSo8Wghdw6Pfsti0o+guc4Q5g1Rx",
	"QqaMC0h6G1rk/sqEJ3go982kenx+fuoGu6nStRxKsIXgMSAUy63D63MzbqYRvQRt/A2D3nZvgEqqDCTL",
	"OB3RYW/QGwa2OLv1564w4uMMXEeKVnU6nyR0RH8A60snjZpT8c5g8GijcKs43zEBB8WRoB70Ioy6eZoy",
	"vaAjejSH+IJczcHOwdusdkbnUhY+6ntbmv4NtofLfugcnWKZMh126JocnB01S8Fl/9HHG8oRa4jE0GiH",
	"/rNihdU5RGsapt41Lz9HRbg/x+B+LOOvGrRbcxZCX35DHqwczzpYcShDzxEzUf4guWKGZBouucqNWBAU",
	"I8BC8p0jBFxzY7mclb80XLqzuZYY3cuI7gy2/zZ9kOWZ313iQ3XCnOLw7Xp7d4kt/dJv/bJyx3bXUKtM",
	"gbWE6qvl7bmnnjyLDIS9lFt1UNcz0iZ/vyApsmD5G8w5NFjmYH0VHXd9E31UzGno1zKXoNTQZHuOWeSS",
	"32nIFbdzwmRFJ78V0y8TeacB21Nhw37HQZL0nQZWnHuF+ezn7XHkZ89bGgRrcUPK6fROgM0xtsu95TU9",
	"76fHd3Bb66ru/duQONcapCU4V4Fz+d5ayWcFq7sH84buRekBTWKVi8SxrsgqDmDA/ticX1doswS6VEHY",
	"rTyCU0swJQpc/hkAAP//",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
