//go:build go1.22

// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/flate"
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/oapi-codegen/runtime"
)

// Defines values for AccountStatus.
const (
	Active AccountStatus = "active"
	Closed AccountStatus = "closed"
)

// Valid indicates whether the value is a known member of the AccountStatus enum.
func (e AccountStatus) Valid() bool {
	switch e {
	case Active:
		return true
	case Closed:
		return true
	default:
		return false
	}
}

// Defines values for ErrorCode.
const (
	AccountClosed       ErrorCode = "account_closed"
	AccountNotFound     ErrorCode = "account_not_found"
	HolderConflict      ErrorCode = "holder_conflict"
	IdempotencyConflict ErrorCode = "idempotency_conflict"
	InsufficientFunds   ErrorCode = "insufficient_funds"
	InternalServerError ErrorCode = "internal_server_error"
	LedgerClosed        ErrorCode = "ledger_closed"
	LedgerNotFound      ErrorCode = "ledger_not_found"
)

// Valid indicates whether the value is a known member of the ErrorCode enum.
func (e ErrorCode) Valid() bool {
	switch e {
	case AccountClosed:
		return true
	case AccountNotFound:
		return true
	case HolderConflict:
		return true
	case IdempotencyConflict:
		return true
	case InsufficientFunds:
		return true
	case InternalServerError:
		return true
	case LedgerClosed:
		return true
	case LedgerNotFound:
		return true
	default:
		return false
	}
}

// Defines values for JournalEntryKind.
const (
	Payment    JournalEntryKind = "payment"
	Settlement JournalEntryKind = "settlement"
	Transfer   JournalEntryKind = "transfer"
)

// Valid indicates whether the value is a known member of the JournalEntryKind enum.
func (e JournalEntryKind) Valid() bool {
	switch e {
	case Payment:
		return true
	case Settlement:
		return true
	case Transfer:
		return true
	default:
		return false
	}
}

// Defines values for PayableAccountKind.
const (
	Payable PayableAccountKind = "payable"
)

// Valid indicates whether the value is a known member of the PayableAccountKind enum.
func (e PayableAccountKind) Valid() bool {
	switch e {
	case Payable:
		return true
	default:
		return false
	}
}

// Defines values for PostJournalEntryResponseState.
const (
	Posted PostJournalEntryResponseState = "posted"
)

// Valid indicates whether the value is a known member of the PostJournalEntryResponseState enum.
func (e PostJournalEntryResponseState) Valid() bool {
	switch e {
	case Posted:
		return true
	default:
		return false
	}
}

// Defines values for ValidationErrorCode.
const (
	ValidationErrorCodeValidationError ValidationErrorCode = "validation_error"
)

// Valid indicates whether the value is a known member of the ValidationErrorCode enum.
func (e ValidationErrorCode) Valid() bool {
	switch e {
	case ValidationErrorCodeValidationError:
		return true
	default:
		return false
	}
}

// Defines values for ValidationErrorDetailCode.
const (
	InvalidFormat ValidationErrorDetailCode = "invalid_format"
	InvalidType   ValidationErrorDetailCode = "invalid_type"
	InvalidValue  ValidationErrorDetailCode = "invalid_value"
	MaxLength     ValidationErrorDetailCode = "max_length"
	MinLength     ValidationErrorDetailCode = "min_length"
	Required      ValidationErrorDetailCode = "required"
	UnknownField  ValidationErrorDetailCode = "unknown_field"
)

// Valid indicates whether the value is a known member of the ValidationErrorDetailCode enum.
func (e ValidationErrorDetailCode) Valid() bool {
	switch e {
	case InvalidFormat:
		return true
	case InvalidType:
		return true
	case InvalidValue:
		return true
	case MaxLength:
		return true
	case MinLength:
		return true
	case Required:
		return true
	case UnknownField:
		return true
	default:
		return false
	}
}

// Defines values for ValidationErrorDetailLocation.
const (
	Body    ValidationErrorDetailLocation = "body"
	Header  ValidationErrorDetailLocation = "header"
	Path    ValidationErrorDetailLocation = "path"
	Query   ValidationErrorDetailLocation = "query"
	Request ValidationErrorDetailLocation = "request"
)

// Valid indicates whether the value is a known member of the ValidationErrorDetailLocation enum.
func (e ValidationErrorDetailLocation) Valid() bool {
	switch e {
	case Body:
		return true
	case Header:
		return true
	case Path:
		return true
	case Query:
		return true
	case Request:
		return true
	default:
		return false
	}
}

// AccountBalances defines model for AccountBalances.
type AccountBalances struct {
	// CreditsPending Total pending credit amount in minor units.
	//
	// Example: 0
	CreditsPending int64 `json:"credits_pending"`

	// CreditsPosted Total posted credit amount in minor units.
	//
	// Example: 10000
	CreditsPosted int64 `json:"credits_posted"`

	// DebitsPending Total pending debit amount in minor units.
	//
	// Example: 200
	DebitsPending int64 `json:"debits_pending"`

	// DebitsPosted Total posted debit amount in minor units.
	//
	// Example: 0
	DebitsPosted int64 `json:"debits_posted"`
}

// AccountReference Stable opaque reference assigned to an account by the ledger.
//
// Example: acct_01K33YV8M82N9MXP4E7J6B1QWK
type AccountReference = string

// AccountStatus Whether the payable account itself is active or closed.
//
// Example: active
type AccountStatus string

// AvailableBalance Derived available amount in minor units (credits_posted - debits_posted - debits_pending).
//
// Example: 9800
type AvailableBalance = int64

// CreatePayableAccountRequest defines model for CreatePayableAccountRequest.
type CreatePayableAccountRequest struct {
	ExternalID string `json:"external_id"`
	Name       string `json:"name"`
}

// CreatePayableAccountResponse defines model for CreatePayableAccountResponse.
type CreatePayableAccountResponse struct {
	// Available Derived available amount in minor units (credits_posted - debits_posted - debits_pending).
	//
	// Example: 9800
	Available AvailableBalance `json:"available"`
	Balances  AccountBalances  `json:"balances"`
	CreatedAt time.Time        `json:"created_at"`

	// ExternalID Example: merchant_123
	ExternalID string `json:"external_id"`

	// HolderReference Stable opaque reference assigned to a holder by the ledger.
	//
	// Example: hld_01K33YVADP5Z8B0T3X2Q91C6RH
	HolderReference HolderReference `json:"holder_reference"`

	// Kind Example: payable
	Kind PayableAccountKind `json:"kind"`

	// LedgerSlug Opaque identifier assigned to the ledger.
	//
	// Example: ngn_ng
	LedgerSlug LedgerSlug `json:"ledger_slug"`

	// Name Example: Acme Ltd
	Name string `json:"name"`

	// Reference Stable opaque reference assigned to an account by the ledger.
	//
	// Example: acct_01K33YV8M82N9MXP4E7J6B1QWK
	Reference AccountReference `json:"reference"`

	// Status Whether the payable account itself is active or closed.
	//
	// Example: active
	Status AccountStatus `json:"status"`
}

// ErrorCode defines model for ErrorCode.
type ErrorCode string

// ErrorInfo defines model for ErrorInfo.
type ErrorInfo struct {
	Code ErrorCode `json:"code"`
}

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	Error   ErrorInfo `json:"error"`
	Message string    `json:"message"`
}

// GetAccountResponse Example: {"available":9800,"balances":{"credits_pending":0,"credits_posted":10000,"debits_pending":200,"debits_posted":0},"created_at":"2026-09-08T10:30:00Z","holder_reference":"hld_01K33YVADP5Z8B0T3X2Q91C6RH","kind":"payable","ledger_slug":"ngn_ng","name":"Acme Ltd","reference":"acct_01K33YV8M82N9MXP4E7J6B1QWK","status":"active"}
type GetAccountResponse struct {
	// Available Derived available amount in minor units (credits_posted - debits_posted - debits_pending).
	//
	// Example: 9800
	Available AvailableBalance `json:"available"`
	Balances  AccountBalances  `json:"balances"`
	CreatedAt time.Time        `json:"created_at"`

	// HolderReference Stable opaque reference assigned to a holder by the ledger.
	//
	// Example: hld_01K33YVADP5Z8B0T3X2Q91C6RH
	HolderReference HolderReference `json:"holder_reference"`

	// Kind Example: payable
	Kind PayableAccountKind `json:"kind"`

	// LedgerSlug Opaque identifier assigned to the ledger.
	//
	// Example: ngn_ng
	LedgerSlug LedgerSlug `json:"ledger_slug"`

	// Name Example: Acme Ltd
	Name string `json:"name"`

	// Reference Stable opaque reference assigned to an account by the ledger.
	//
	// Example: acct_01K33YV8M82N9MXP4E7J6B1QWK
	Reference AccountReference `json:"reference"`

	// Status Whether the payable account itself is active or closed.
	//
	// Example: active
	Status AccountStatus `json:"status"`
}

// HealthResponse defines model for HealthResponse.
type HealthResponse struct {
	// Status Example: ok
	Status string `json:"status"`
}

// HolderReference Stable opaque reference assigned to a holder by the ledger.
//
// Example: hld_01K33YVADP5Z8B0T3X2Q91C6RH
type HolderReference = string

// IdempotencyKey Caller-generated identifier used to make a ledger operation idempotent.
//
// Example: payment_123
type IdempotencyKey = string

// JournalEntryKind Business classification of a journal entry.
type JournalEntryKind string

// JournalRef Stable opaque reference assigned to a journal entry by the ledger.
//
// Example: jrn_01K33YW0MDHJ9E4N7Z2QPV6R8K
type JournalRef = string

// LedgerSlug Opaque identifier assigned to the ledger.
//
// Example: ngn_ng
type LedgerSlug = string

// PayableAccountKind Example: payable
type PayableAccountKind string

// PostJournalEntryLine defines model for PostJournalEntryLine.
type PostJournalEntryLine struct {
	// Amount Positive amount expressed in the ledger's minor units.
	//
	// Example: 10000
	Amount int64 `json:"amount"`

	// CreditAccountRef Stable opaque reference assigned to an account by the ledger.
	//
	// Example: acct_01K33YV8M82N9MXP4E7J6B1QWK
	CreditAccountRef AccountReference `json:"credit_account_ref"`

	// DebitAccountRef Stable opaque reference assigned to an account by the ledger.
	//
	// Example: acct_01K33YV8M82N9MXP4E7J6B1QWK
	DebitAccountRef AccountReference `json:"debit_account_ref"`
}

// PostJournalEntryRequest defines model for PostJournalEntryRequest.
type PostJournalEntryRequest struct {
	Description *string    `json:"description,omitempty"`
	EffectiveAt *time.Time `json:"effective_at,omitempty"`

	// Kind Business classification of a journal entry.
	Kind  JournalEntryKind       `json:"kind"`
	Lines []PostJournalEntryLine `json:"lines"`
}

// PostJournalEntryResponse defines model for PostJournalEntryResponse.
type PostJournalEntryResponse struct {
	CreatedAt   time.Time `json:"created_at"`
	Description *string   `json:"description,omitempty"`
	EffectiveAt time.Time `json:"effective_at"`

	// JournalRef Stable opaque reference assigned to a journal entry by the ledger.
	//
	// Example: jrn_01K33YW0MDHJ9E4N7Z2QPV6R8K
	JournalRef JournalRef `json:"journal_ref"`

	// Kind Business classification of a journal entry.
	Kind JournalEntryKind `json:"kind"`

	// LedgerSlug Opaque identifier assigned to the ledger.
	//
	// Example: ngn_ng
	LedgerSlug LedgerSlug                    `json:"ledger_slug"`
	State      PostJournalEntryResponseState `json:"state"`
}

// PostJournalEntryResponseState defines model for PostJournalEntryResponse.State.
type PostJournalEntryResponseState string

// ValidationError defines model for ValidationError.
type ValidationError struct {
	Code    ValidationErrorCode     `json:"code"`
	Details []ValidationErrorDetail `json:"details"`
}

// ValidationErrorCode defines model for ValidationError.Code.
type ValidationErrorCode string

// ValidationErrorDetail defines model for ValidationErrorDetail.
type ValidationErrorDetail struct {
	Code ValidationErrorDetailCode `json:"code"`

	// Field Example: external_id
	Field    string                        `json:"field"`
	Location ValidationErrorDetailLocation `json:"location"`

	// Message Example: external_id is required
	Message string `json:"message"`
}

// ValidationErrorDetailCode defines model for ValidationErrorDetail.Code.
type ValidationErrorDetailCode string

// ValidationErrorDetailLocation defines model for ValidationErrorDetail.Location.
type ValidationErrorDetailLocation string

// ValidationErrorResponse defines model for ValidationErrorResponse.
type ValidationErrorResponse struct {
	Error ValidationError `json:"error"`

	// Message Example: Request validation failed.
	Message string `json:"message"`
}

// InvalidRequest defines model for InvalidRequest.
type InvalidRequest = ValidationErrorResponse

// PostJournalEntryParams defines parameters for PostJournalEntry.
type PostJournalEntryParams struct {
	// IdempotencyKey Caller-generated key that uniquely identifies this posting within the ledger.
	IdempotencyKey IdempotencyKey `json:"Idempotency-Key"`
}

// CreatePayableAccountJSONRequestBody defines body for CreatePayableAccount for application/json ContentType.
type CreatePayableAccountJSONRequestBody = CreatePayableAccountRequest

// PostJournalEntryJSONRequestBody defines body for PostJournalEntry for application/json ContentType.
type PostJournalEntryJSONRequestBody = PostJournalEntryRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// GetHealth Check whether the service is running
	// (GET /health)
	GetHealth(w http.ResponseWriter, r *http.Request)
	// CreatePayableAccount Create a payable account in a ledger
	// (POST /ledgers/{slug}/accounts)
	CreatePayableAccount(w http.ResponseWriter, r *http.Request, slug LedgerSlug)
	// GetAccount Get a payable account and its balance
	// (GET /ledgers/{slug}/accounts/{account_reference})
	GetAccount(w http.ResponseWriter, r *http.Request, slug LedgerSlug, accountReference AccountReference)
	// PostJournalEntry Post a journal entry to a ledger
	// (POST /ledgers/{slug}/entries)
	PostJournalEntry(w http.ResponseWriter, r *http.Request, slug LedgerSlug, params PostJournalEntryParams)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// GetHealth operation middleware
func (siw *ServerInterfaceWrapper) GetHealth(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetHealth(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreatePayableAccount operation middleware
func (siw *ServerInterfaceWrapper) CreatePayableAccount(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "slug" -------------
	var slug LedgerSlug

	err = runtime.BindStyledParameterWithOptions("simple", "slug", r.PathValue("slug"), &slug, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "slug", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreatePayableAccount(w, r, slug)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetAccount operation middleware
func (siw *ServerInterfaceWrapper) GetAccount(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "slug" -------------
	var slug LedgerSlug

	err = runtime.BindStyledParameterWithOptions("simple", "slug", r.PathValue("slug"), &slug, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "slug", Err: err})
		return
	}

	// ------------- Path parameter "account_reference" -------------
	var accountReference AccountReference

	err = runtime.BindStyledParameterWithOptions("simple", "account_reference", r.PathValue("account_reference"), &accountReference, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "account_reference", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetAccount(w, r, slug, accountReference)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostJournalEntry operation middleware
func (siw *ServerInterfaceWrapper) PostJournalEntry(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "slug" -------------
	var slug LedgerSlug

	err = runtime.BindStyledParameterWithOptions("simple", "slug", r.PathValue("slug"), &slug, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "slug", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params PostJournalEntryParams

	headers := r.Header

	// ------------- Required header parameter "Idempotency-Key" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("Idempotency-Key")]; found {
		var IdempotencyKey IdempotencyKey
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "Idempotency-Key", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "Idempotency-Key", valueList[0], &IdempotencyKey, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true, Type: "string", Format: ""})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "Idempotency-Key", Err: err})
			return
		}

		params.IdempotencyKey = IdempotencyKey

	} else {
		err := fmt.Errorf("Header parameter Idempotency-Key is required, but not found")
		siw.ErrorHandlerFunc(w, r, &RequiredHeaderError{ParamName: "Idempotency-Key", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostJournalEntry(w, r, slug, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

// ServeMux is an abstraction of [http.ServeMux].
type ServeMux interface {
	HandleFunc(pattern string, handler func(http.ResponseWriter, *http.Request))
	http.Handler
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/health", wrapper.GetHealth)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/ledgers/{slug}/accounts", wrapper.CreatePayableAccount)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/ledgers/{slug}/accounts/{account_reference}", wrapper.GetAccount)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/ledgers/{slug}/entries", wrapper.PostJournalEntry)

	return m
}

type InvalidRequestJSONResponse ValidationErrorResponse

type GetHealthRequestObject struct {
}

type GetHealthResponseObject interface {
	VisitGetHealthResponse(w http.ResponseWriter) error
}

type GetHealth200JSONResponse HealthResponse

func (response GetHealth200JSONResponse) VisitGetHealthResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type CreatePayableAccountRequestObject struct {
	Slug LedgerSlug `json:"slug"`
	Body *CreatePayableAccountJSONRequestBody
}

type CreatePayableAccountResponseObject interface {
	VisitCreatePayableAccountResponse(w http.ResponseWriter) error
}

type CreatePayableAccount200JSONResponse CreatePayableAccountResponse

func (response CreatePayableAccount200JSONResponse) VisitCreatePayableAccountResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type CreatePayableAccount201JSONResponse CreatePayableAccountResponse

func (response CreatePayableAccount201JSONResponse) VisitCreatePayableAccountResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)
	_, err := buf.WriteTo(w)
	return err
}

type CreatePayableAccount400JSONResponse struct{ InvalidRequestJSONResponse }

func (response CreatePayableAccount400JSONResponse) VisitCreatePayableAccountResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type CreatePayableAccount404JSONResponse ErrorResponse

func (response CreatePayableAccount404JSONResponse) VisitCreatePayableAccountResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type CreatePayableAccount409JSONResponse ErrorResponse

func (response CreatePayableAccount409JSONResponse) VisitCreatePayableAccountResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(409)
	_, err := buf.WriteTo(w)
	return err
}

type CreatePayableAccount500JSONResponse ErrorResponse

func (response CreatePayableAccount500JSONResponse) VisitCreatePayableAccountResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type GetAccountRequestObject struct {
	Slug             LedgerSlug       `json:"slug"`
	AccountReference AccountReference `json:"account_reference"`
}

type GetAccountResponseObject interface {
	VisitGetAccountResponse(w http.ResponseWriter) error
}

type GetAccount200JSONResponse GetAccountResponse

func (response GetAccount200JSONResponse) VisitGetAccountResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetAccount400JSONResponse struct{ InvalidRequestJSONResponse }

func (response GetAccount400JSONResponse) VisitGetAccountResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type GetAccount404JSONResponse ErrorResponse

func (response GetAccount404JSONResponse) VisitGetAccountResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type GetAccount500JSONResponse ErrorResponse

func (response GetAccount500JSONResponse) VisitGetAccountResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type PostJournalEntryRequestObject struct {
	Slug   LedgerSlug `json:"slug"`
	Params PostJournalEntryParams
	Body   *PostJournalEntryJSONRequestBody
}

type PostJournalEntryResponseObject interface {
	VisitPostJournalEntryResponse(w http.ResponseWriter) error
}

type PostJournalEntry200JSONResponse PostJournalEntryResponse

func (response PostJournalEntry200JSONResponse) VisitPostJournalEntryResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type PostJournalEntry201JSONResponse PostJournalEntryResponse

func (response PostJournalEntry201JSONResponse) VisitPostJournalEntryResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)
	_, err := buf.WriteTo(w)
	return err
}

type PostJournalEntry400JSONResponse struct{ InvalidRequestJSONResponse }

func (response PostJournalEntry400JSONResponse) VisitPostJournalEntryResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type PostJournalEntry404JSONResponse ErrorResponse

func (response PostJournalEntry404JSONResponse) VisitPostJournalEntryResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type PostJournalEntry409JSONResponse ErrorResponse

func (response PostJournalEntry409JSONResponse) VisitPostJournalEntryResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(409)
	_, err := buf.WriteTo(w)
	return err
}

type PostJournalEntry500JSONResponse ErrorResponse

func (response PostJournalEntry500JSONResponse) VisitPostJournalEntryResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// GetHealth Check whether the service is running
	// (GET /health)
	GetHealth(ctx context.Context, request GetHealthRequestObject) (GetHealthResponseObject, error)
	// CreatePayableAccount Create a payable account in a ledger
	// (POST /ledgers/{slug}/accounts)
	CreatePayableAccount(ctx context.Context, request CreatePayableAccountRequestObject) (CreatePayableAccountResponseObject, error)
	// GetAccount Get a payable account and its balance
	// (GET /ledgers/{slug}/accounts/{account_reference})
	GetAccount(ctx context.Context, request GetAccountRequestObject) (GetAccountResponseObject, error)
	// PostJournalEntry Post a journal entry to a ledger
	// (POST /ledgers/{slug}/entries)
	PostJournalEntry(ctx context.Context, request PostJournalEntryRequestObject) (PostJournalEntryResponseObject, error)
}

type StrictHandlerFunc func(ctx context.Context, w http.ResponseWriter, r *http.Request, request any) (any, error)
type StrictMiddlewareFunc func(f StrictHandlerFunc, operationID string) StrictHandlerFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	if options.RequestErrorHandlerFunc == nil {
		options.RequestErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	if options.ResponseErrorHandlerFunc == nil {
		options.ResponseErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		}
	}
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// GetHealth operation middleware
func (sh *strictHandler) GetHealth(w http.ResponseWriter, r *http.Request) {
	var request GetHealthRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetHealth(ctx, request.(GetHealthRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetHealth")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetHealthResponseObject); ok {
		if err := validResponse.VisitGetHealthResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// CreatePayableAccount operation middleware
func (sh *strictHandler) CreatePayableAccount(w http.ResponseWriter, r *http.Request, slug LedgerSlug) {
	var request CreatePayableAccountRequestObject

	request.Slug = slug

	var body CreatePayableAccountJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.CreatePayableAccount(ctx, request.(CreatePayableAccountRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreatePayableAccount")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(CreatePayableAccountResponseObject); ok {
		if err := validResponse.VisitCreatePayableAccountResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetAccount operation middleware
func (sh *strictHandler) GetAccount(w http.ResponseWriter, r *http.Request, slug LedgerSlug, accountReference AccountReference) {
	var request GetAccountRequestObject

	request.Slug = slug
	request.AccountReference = accountReference

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetAccount(ctx, request.(GetAccountRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetAccount")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetAccountResponseObject); ok {
		if err := validResponse.VisitGetAccountResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// PostJournalEntry operation middleware
func (sh *strictHandler) PostJournalEntry(w http.ResponseWriter, r *http.Request, slug LedgerSlug, params PostJournalEntryParams) {
	var request PostJournalEntryRequestObject

	request.Slug = slug
	request.Params = params

	var body PostJournalEntryJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.PostJournalEntry(ctx, request.(PostJournalEntryRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PostJournalEntry")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(PostJournalEntryResponseObject); ok {
		if err := validResponse.VisitPostJournalEntryResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"7Ft5c9s2Fv8qGGxntu3SNi3Zjq39Yydx0sZ12nUdT9ttmtVA5KOEmAQYAHSsZvTdd3CQBA+dcdJuJ/9Z",
	"xPXu33sP8Hsc8SznDJiSePQeC5A5ZxLMjwt2R1IaX8PbAqTSXyLOFDDzJ8nzlEZEUc4O3kjO9DcZzSAj",
	"+q8vBCR4hP92UG9/YEflwU96U7PwmRBcXLsj8WKxCHAMMhI016N4hG9mgIQ9HsUcJGJcIUkUlckcqRmg",
	"x1cXSBMlSKT2sd7AnaKJeBxFvGDqCUkJiyxLJI6p3pukV4LnIBTV3xOSSghw7n16jyMBMVVynAOLKZvq",
	"Ty3iuCIpcsPITkck00ciylBGGReoYFTJfRxguCdZngIehQFOuMiIwiNMmTo5wgHOKKNZkZlBNc/BDsEU",
	"BF4ENSVcKoiXEmJGN6fjMAzD7WmJYbKFUMzsDWgZfAAlmwhlUzq2pWIRYG2eVGgKXrWFE3RsqE11R7ev",
	"qzP45A1ESjPqzPgaEhDAIujy+lKRSQqI5+RtoR3GTURESjplECPFEWGI2I3QxPpOCvEURIN/TKJIjcPD",
	"y+HwPz+dfn86+OHs+1+ujp49+u7kyeGPP19qcZD7F8CmaoZHJ0dGOuXPw4p2qYTl9n7vrnL2vQykJFPr",
	"XN4uOCukMo4N9xFAjE6OUDQj2qNBSNw4op47AQRZruZGB05CLxVRheyK5+cZqBkIw3RO5kZWpSyokpAm",
	"iEpEIkXvAHGBopRLiI1gmFb8K2zHtLrMkFaTLzM32ORe03VHaKqPcyGoS9pTEPQOYkTKmf1Gir5s2gna",
	"Qw1D8n5bS/uqodaz0x3861wAUXBl5VXZYAUFzWAJ9woEI+mYxi31Do6P21aSE6Vn4xHe//q3317uf437",
	"LGfK9xjJ9MdnbvOLp7ua1OD4eBub8kn0RycpYbc1sWZoAoigUuWLAFuaH0YEf2ZOW6HPNwAnhL5Y1m9U",
	"LgHYDp8rl1mXb3S8cBHgiZcTrFzbSiEsGhMF8ZgYN6icKiYK9hTNegNByz3q2JGBiGaEqfHhYIjXR9Ne",
	"n1gEeMbTGMRY+BCxiq3nZn6NKIsA31IWr1vW1NulXrEIsMWRsUyL6boNXpipL/VMz1VqcTyOMkAvVLxG",
	"FMb2NmS1g546R6yAYoOVDlXaBt8RuU9TUyhBn3c4iVfEBJ5Be/bZsLc+jzI59DmPrSQdXrnTGVfjhBfm",
	"GPfJAVhlMhFnSUojpc+3/DZWld+qZZTJIkloRIGpcVKwWJNIY8hyroBFc39DDSaGawniDsQYNKkeE7U2",
	"DRMXLOHb5uiO71VqrAXUVqFZvVSmO4Yly+QmNBl+FwF2od1E9lVG36K+XBbgtlxrRr4FtW2QrZyxEWFt",
	"BuFHzU55FHYLFVditGuGgf/RTQ1bkRUPwsHJXni2F57eHIajYTgKw19xX6TDszQuU9bHT6+Ofz19Et4M",
	"fxn8eHZ4fnL9vHS0EXapX8s5R5hN2djEVxdavSDkH7M+NS7DSpkRLv6fIeszpHxySPHxowdempDi0MNh",
	"yQeCyHMgqZrtGPFq1mup81u8Ln65Zb3ktGxpt4IXWRmuKnfXho4tqt1FgC9qHLyEeZfsc5KmIPamwEBo",
	"dSAaA1M0oSBQIS3ZGbnVebalFmk5mwIAVRirmizkZJ5BnUD+xauOAH/HC51TPGNKzC9dgGlK+UkhKQMp",
	"UZRqe0hclxLxBBH0xi5HoNf7Jb6To/YlUCoF90MJwmQCPWnLClHZPSv6OQPEkxFyRwSoPiFA1QEec9c6",
	"guxm8w3+Vpn+G8Gc6f8cfv/0+Xdnz45+ePTr4Mern06uTy+3Nn0vDHco/7cl2TN2n+ZlBFaw7BMybBAy",
	"9A3pv6/I3u/h3tnrf3z5r9G4+vHV1188lJWfDNcYecSZIpQholAKRCrUWtCy+nJ6yt+BiIjUctATJCIs",
	"RqzIJvpvCTmx0WIyR5KyaQqoYDEIGXEBFkV6UNSrBsrE53UrbjiY6Ojyikvlu9kLyqDb8rGNqq62r7ik",
	"ppPmOllwnwuQOrpR5in773L7zjS5t/2qs8FgOHw0CIcnp8dHjx6dmOlVN+uw081arW+7qqNtTaobRbLI",
	"cy60DhzX3nGVm08NxgqkZoSh30HwnkjGkN87tvnyuCyyhHX7bVMPk0l/2CZ9fezGjr20BqUN9GF424iW",
	"tg4b1tNwwGOn1k+BYMdh+KkQDJIETIGwVT6+STLdwUadSmss1Aupgmxtgtrr+gvjehd2/aFTSvmzIpUI",
	"QeZrxO8W1SIrQ2DGBVjHOQzDCsQs7f5xS+KsRlh/Ua/nWQI7nUuXSNuzNrPkndLkXYqwtm+sxuDdDMvJ",
	"bZPA4aUnH2KRuxZ3umJotLk6l2ZLSg2fxSV1lN27JcO1dVPrKnvH7lXJTu03K1plMShC0809ukXiU7Pc",
	"uPRSH+7tk9UnbyAId8qHiaMiIcDUvkQYm3Prn87A6w93JC3ABoxxaj3FxK76R8FuGX/HxgmFNO4VsB1p",
	"VLPN9u0aL0y5rTfarGjwM7ChyXhbgNDBcgYkNgnKhMfzXnK87mAvQYhK5Elqmw5iRWnJdFCqujx0A1V/",
	"zDZp272WicPlFqh2IJQQmto73IftqeoV1DWqm3nv85ubK/MeJeHCy3ORBHFHI9CkKKoMvTas6ck4wHcg",
	"pN0h3D/cDzWTPAdGcopHeLgf7g+d2Ri5HcxMq0b/OQUT5asWwUWMR/hbULaZY7qX3mOeQRg+2AueVrto",
	"ycMdx7g2UEv03L3QKbKMiDke4fMZRLfonXc9760RBWOljg6sLOXBex21FwcuCzWMaRDoyqHvotHIUZAM",
	"TIo3evUeU2YqISMt1/11sFBbhRIFBBsKxserxeug9Psn2rkfSvir7uVbyY0mffER7WDlbW6PVTxmrgkQ",
	"kbR61/WOSJQLuKO8kOkc6WNSUBD/0xgE3FOpKJvWDzZ0uFOFYNq7FwEehId/GD83PQ9KNDsuazD0HVl5",
	"9x1b6eWg9dLOLDvagC3vsqYKqBZGu1eAfvAsI5BOwc2oIXUzIW3zaA/iMgpWr/eMQp1kzjZn0diubeie",
	"lzeMWq9VLNGnuoavtTGlbcnOlOgdVTNdA1TmZKfq8GtShh4Bti9IG/J77k5iNgXRiLP2MBv9rDzO7X1q",
	"hwMnLSpRdeO6lMDmjW6feqtt9q2eHl7Bba4b/Z2oEAKYQia3Nio/3ij4rLDq/ivlBu8l9IBAES/S2NWZ",
	"NqoYAh3tD23zmx7ahEATKhDpPkxj1S3ASgg8eO+1ZGw/Z+FlB00yr0EJCncgTcXcPpKwGMF9ziVINOFq",
	"hqiSKF72Qk3P1hNMLzKdazt31mt2AyH30c2MSpMTee6v90elHlFE5AxxgQTcASsqWkxDsJPZ/DE4HvTu",
	"35H6zof1tONef0TQ7nkTsAW0GbQwui9R2Dq+toTyvvGT4Z7tQ1vqfuDqG4NznZjaZqMJRc2u9Kp4230f",
	"04g7TqgNTK3i/XLqevFxg7C/ObAvPjK0c7FGxJ9Df2/o/xZUT9wvw+qkfPnRE/uB6TC+ovpptyw/fcRc",
	"c/F9C3OkZkShgtG3BaTz+nZQIqVRQzOmMUVHl4aL7pt+j07Qyt6Jo9+7fd+7hPnOrLRu8T9aIbfshuQT",
	"F3FL29sPXMDZG+mPWb5tw4n22uZduWHDNJT/RPj1uL7ojz8D2MME6xq27MMMF6PbYpYPU7O63foKvl7l",
	"blT6tZ7l9qqxUfw13uguL6C9SSZEt1zbvFFKuEAxTQzh9irOvpRZSmzv6+AGyRetY9uldEVDE0r9t8jf",
	"mKfITfF6//FkwRQJkErQyNTr7wxYT8DdAK8WeM+z5yYH3jgy43+par8E45Ziqthetro/F/pLsz0NTp33",
	"WebJVlXkLxb/CwAA//8=",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
